
package StyleManagement;

import com.github.lgooddatepicker.components.DatePickerSettings;
import MainSystem.AutoIdGenerator;
import MainSystem.DB_Connect;
import MainSystem.MainWindow;
import static MainSystem.MainWindow.db_con;
import java.awt.Color;
import java.awt.Image;
import java.awt.Toolkit;
import java.io.ByteArrayOutputStream;
import java.io.File;
import java.io.FileInputStream;
import java.io.FileNotFoundException;
import java.io.IOException;
import java.io.InputStream;
import java.sql.Blob;
import java.sql.SQLException;
import java.util.Arrays;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import net.proteanit.sql.DbUtils;


/**
 *
 * @author Dinushka
 */
public class CreateDesign extends javax.swing.JInternalFrame {
DefaultTableModel model;
int RowCountjTable2;
CreateDesignModel NewSalesDesignModel ;



        String LogNo;
        String CustomerId;
        String CustomerName;
        String CustomerCompanyName;
        String CustomerPhone;
        String CustomerEmail;
        String CustomerAddres;
        FileInputStream fis;
        int filelenth;
        


    /**
     * Creates new form SalesDesignInquiry
     */
    public CreateDesign() {
        initComponents();
        generate_sdi();
        datePicker2.setDateToToday();
    NewSalesDesignModel = new CreateDesignModel();
     jTable1.setModel(DbUtils.resultSetToTableModel(NewSalesDesignModel.ViewAll()));
     jTable1.setDefaultRenderer(Object.class, new CreateDesign.MyCellRenderer());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel5 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jTextFieldCustomerId = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        DatePickerSettings dateSettings = new DatePickerSettings();
        dateSettings.setFormatForDatesCommonEra("yyyy/MM/dd");
        dateSettings.setFormatForDatesBeforeCommonEra("uuuu/MM/dd");
        datePicker2 = new com.github.lgooddatepicker.components.DatePicker(dateSettings);
        jButton4 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jTextFieldSalesDesignInquiryId = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        jTextFieldDescription = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        jLabelImg = new javax.swing.JLabel();
        jTextField3 = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jTextFieldDescription1 = new javax.swing.JTextField();
        jButton3 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jLabelImg1 = new javax.swing.JLabel();
        jButton7 = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();

        setResizable(true);
        setTitle("Create Design Management");
        setMaximumSize(new java.awt.Dimension(1365, 620));
        setMinimumSize(new java.awt.Dimension(1365, 620));
        setPreferredSize(new java.awt.Dimension(1365, 620));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTabbedPane1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N

        jPanel5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        jPanel5.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 1310, 240));

        jButton1.setText(" Select to ADD Design");
        jPanel5.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 500, -1, -1));

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(jTable2);

        jPanel5.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 270, 1300, 180));

        jTabbedPane1.addTab("Main ", jPanel5);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTextFieldCustomerId.setEditable(false);
        jTextFieldCustomerId.setName("Customer ID"); // NOI18N
        jTextFieldCustomerId.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldCustomerIdActionPerformed(evt);
            }
        });
        jPanel2.add(jTextFieldCustomerId, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 50, 110, -1));
        jTextFieldCustomerId.getAccessibleContext().setAccessibleName("");

        jLabel2.setText("Design ID");
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 52, -1, -1));

        jLabel7.setText("Date");
        jPanel2.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 50, -1, -1));

        datePicker2.setName(""); // NOI18N
        jPanel2.add(datePicker2, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 50, -1, -1));

        jButton4.setText("ADD Design");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 480, -1, -1));

        jButton6.setText("Reset All");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton6, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 480, -1, -1));

        jTextFieldSalesDesignInquiryId.setEditable(false);
        jTextFieldSalesDesignInquiryId.setName("Sales Design Inquiry ID"); // NOI18N
        jTextFieldSalesDesignInquiryId.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldSalesDesignInquiryIdActionPerformed(evt);
            }
        });
        jPanel2.add(jTextFieldSalesDesignInquiryId, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 90, 110, -1));

        jLabel12.setText("Sales Or Market Design Inquiry ID");
        jPanel2.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 90, -1, -1));

        jTextFieldDescription.setName("Description"); // NOI18N
        jPanel2.add(jTextFieldDescription, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 160, 380, 60));

        jLabel1.setText("Description");
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 180, -1, -1));

        jLabel14.setText("Designer name");
        jPanel2.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 120, -1, -1));

        jTextField2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField2ActionPerformed(evt);
            }
        });
        jPanel2.add(jTextField2, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 120, 80, -1));

        jButton2.setText("Pattern Choose File");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(1030, 410, -1, -1));

        jLabelImg.setText("Image## Do not move##");
        jLabelImg.setMaximumSize(new java.awt.Dimension(300, 300));
        jLabelImg.setMinimumSize(new java.awt.Dimension(300, 300));
        jLabelImg.setPreferredSize(new java.awt.Dimension(300, 300));
        jPanel2.add(jLabelImg, new org.netbeans.lib.awtextra.AbsoluteConstraints(940, 40, 300, 300));
        jPanel2.add(jTextField3, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 120, 80, -1));

        jLabel15.setText("Designer Creator's name");
        jPanel2.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 120, -1, -1));

        jLabel3.setText("Note");
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 240, -1, 10));

        jTextFieldDescription1.setName("Description"); // NOI18N
        jPanel2.add(jTextFieldDescription1, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 230, 380, 60));

        jButton3.setText("image Choose File");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(1030, 370, -1, 20));

        jButton5.setText("jButton5");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 380, -1, -1));

        jLabelImg1.setText("Image## Do not move##");
        jLabelImg1.setMaximumSize(new java.awt.Dimension(300, 300));
        jLabelImg1.setMinimumSize(new java.awt.Dimension(300, 300));
        jLabelImg1.setPreferredSize(new java.awt.Dimension(300, 300));
        jPanel2.add(jLabelImg1, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 60, 300, 300));

        jButton7.setText("jButton7");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton7, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 380, -1, -1));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 20, 1270, 520));

        jTabbedPane1.addTab("ADD Design", jPanel1);

        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jTabbedPane1.addTab("Search &  Delete", jPanel3);

        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jTabbedPane1.addTab("Reports", jPanel4);

        getContentPane().add(jTabbedPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1350, 590));

        getAccessibleContext().setAccessibleName("");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextFieldSalesDesignInquiryIdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldSalesDesignInquiryIdActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldSalesDesignInquiryIdActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        clear();        // TODO add your handling code here:
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed

        //  boolean result=customerModel.AddCustomer(jTextFieldCustomerId, jTextFieldCustomerName, jTextFieldCompanyName,jTextFieldPhone,jTextFieldEmail,datePicker2);
        //   if(result)
        {
            JOptionPane.showMessageDialog(null,"Successfully To Added Customer", "InfoBox", JOptionPane.INFORMATION_MESSAGE);
            generate_sdi();
            clear();
        }
        // else
        {
            JOptionPane.showMessageDialog(null,"Failed To Added Customer", "InfoBox", JOptionPane.INFORMATION_MESSAGE);

        }
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jTextFieldCustomerIdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldCustomerIdActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldCustomerIdActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
    JFileChooser fileChooser2 = new JFileChooser();
    fileChooser2.setCurrentDirectory(new File(System.getProperty("user.home")));
    int result = fileChooser2.showOpenDialog(this);
    if (result == JFileChooser.APPROVE_OPTION) {
    File selectedFile = fileChooser2.getSelectedFile();
    System.out.println("Selected pattern file: " + selectedFile.getAbsolutePath());

}
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jTextField2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
    JFileChooser fileChooser1 = new JFileChooser();
    //fileChooser1.setCurrentDirectory(new File(System.getProperty("user.home")));
    int result = fileChooser1.showOpenDialog(this);
    if (result == JFileChooser.APPROVE_OPTION) {
    File selectedFile = fileChooser1.getSelectedFile();
    System.out.println("Selected pattern file: " + selectedFile.getAbsolutePath());
    ImageIcon icon = new ImageIcon(selectedFile.getAbsolutePath());
    jLabelImg.setIcon(icon);
    
        try {
            fis = new FileInputStream(selectedFile);
        } catch (FileNotFoundException ex) {
            System.err.println("5");
            Logger.getLogger(CreateDesign.class.getName()).log(Level.SEVERE, null, ex);
        }
        filelenth=(int)selectedFile.length();
        System.err.println("zzzzzzz");
        DB_Connect dvv =new overideExcute();
        System.err.println("zzzzzzzzzzzzzzzzzz");
        dvv.execute(LogNo);
        System.err.println("11111111111111111111111");
//        try {
//            DB_Connect.DB_PreparedStatement.setBinaryStream(10,(InputStream)fis,(int)selectedFile.length());
//        } catch (SQLException ex) {
//            Logger.getLogger(CreateDesign.class.getName()).log(Level.SEVERE, null, ex);
//        }
//    MainSystem.MainWindow.db_con.execute("INSERT INTO `garmentsystem`.`design_table`\n" +
//"(`patten`)\n" +
//"VALUES(?);");
    } 
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
    DB_Connect.DB_ResultSet = db_con.executeQuery("SELECT `design_table`.`patten`\n" +
"FROM `garmentsystem`.`design_table` where `design_table`.`ID` =1 ;");
    try {
        DB_Connect.DB_ResultSet.next();
        Blob imageBlob=DB_Connect.DB_ResultSet.getBlob("patten");
        //System.out.println(imageBlob.length());
        InputStream binaryStream = imageBlob.getBinaryStream(1, imageBlob.length());
       
        
        ByteArrayOutputStream output = new ByteArrayOutputStream();
        int a1 = binaryStream.read();
        
        while (a1 >= 0) {
          //  System.out.print(a1);
        //output.write((char) a1);
        a1 = binaryStream.read();
        
        }
        //System.out.println(output);
        //System.out.println(Arrays.toString(output.toByteArray()));
        
        
         
        Image myImage = Toolkit.getDefaultToolkit().createImage(output.toByteArray());
        
        output.close();
        ImageIcon icon = new ImageIcon(myImage);
        jLabelImg1.setIcon(icon);
        
    } catch (SQLException ex) {
        Logger.getLogger(CreateDesign.class.getName()).log(Level.SEVERE, null, ex);
    } catch (IOException ex) {
        Logger.getLogger(CreateDesign.class.getName()).log(Level.SEVERE, null, ex);
    }
    
    
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
    System.out.println();
    
    byte[] bytes = ("ava").getBytes();
    for(byte b : bytes) {
    
    System.out.println("byte = " + b);
    System.out.println("binnnary = " + Integer.toBinaryString(b));
   
    
}
    }//GEN-LAST:event_jButton7ActionPerformed
    
    class overideExcute extends DB_Connect{

        @Override
        public boolean execute(String SQL_String) {
            try {
                DB_PreparedStatement =DB_connection.prepareStatement("INSERT INTO `garmentsystem`.`design_table`(`patten`)VALUES(?);");
            } catch (SQLException ex) {
                System.err.println("1");
                Logger.getLogger(CreateDesign.class.getName()).log(Level.SEVERE, null, ex);
                return false;
            }
            
            try {
                DB_PreparedStatement.setBinaryStream(1,(InputStream)fis,filelenth);
            } catch (SQLException ex) {
                System.err.println("2");
                Logger.getLogger(CreateDesign.class.getName()).log(Level.SEVERE, null, ex);
                return false;
            }
            
            try {
                DB_PreparedStatement.executeUpdate();
            } catch (SQLException ex) {
                System.err.println("3");
                Logger.getLogger(CreateDesign.class.getName()).log(Level.SEVERE, null, ex);
                return false;
            }
            
            return (true); 
        }
        
        
        
        
        
 
    }
       
    private void generate_sdi(){
    AutoIdGenerator aid = new AutoIdGenerator();
    jTextFieldCustomerId.setText(aid.generate("cus",Integer.toString(MainWindow.userid)));
    }
    
    private void clear(){
            generate_sdi();

            
    }
    
   
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private com.github.lgooddatepicker.components.DatePicker datePicker2;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabelImg;
    private javax.swing.JLabel jLabelImg1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable jTable2;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextFieldCustomerId;
    private javax.swing.JTextField jTextFieldDescription;
    private javax.swing.JTextField jTextFieldDescription1;
    private javax.swing.JTextField jTextFieldSalesDesignInquiryId;
    // End of variables declaration//GEN-END:variables

public class MyCellRenderer extends javax.swing.table.DefaultTableCellRenderer {
    @Override
    public java.awt.Component getTableCellRendererComponent(javax.swing.JTable table, java.lang.Object value, boolean isSelected, boolean hasFocus, int row, int column)
    {
        final java.awt.Component cellComponent = super.getTableCellRendererComponent(table, value, isSelected, hasFocus, row, column);
     { 
         if((jTable1.getModel().getValueAt(row,8).equals("false")))
         {
         cellComponent.setBackground(Color.red);
         cellComponent.setForeground(Color.black);  
         }
         else if ((jTable1.getModel().getValueAt(row,8).equals("true")))
         {
         cellComponent.setBackground(Color.green);
         cellComponent.setForeground(Color.black);
         }
          else if ((jTable1.getModel().getValueAt(row,8).equals("pending")))
         {
         cellComponent.setBackground(Color.ORANGE);
         cellComponent.setForeground(Color.black);
         }     
     }
        return cellComponent;
}
}
}
