
package ManufacturingPlanning;
 
import MainSystem.AutoIdGenerator;
import MainSystem.AutoDB_Connect;
import MainSystem.MainWindow;
import static MainSystem.MainWindow.autoReport;
import static MainSystem.MainWindow.autoSqlQuery;
import com.github.lgooddatepicker.components.DatePickerSettings;
import java.awt.Color;
//import java.awt.HeadlessException;
import java.sql.SQLException;
import java.time.LocalDate;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import net.proteanit.sql.DbUtils;



/**
 *
 * @author Dinushka
 */
public class CuttingSchedule extends javax.swing.JInternalFrame {

   String matid,matname;

    /**
     * Creates new form SalesDesignInquiry
     */
    public CuttingSchedule() {
        initComponents();
        generate_cdi();
        FillCombo();
        FillComboMaterial();
        FillComboSupervisor();
        FillComboSupervisor2();
        
        AutoDB_Connect.DB_ResultSet = autoSqlQuery.executeQuery("SELECT * FROM garmentsystem.r_Cutting_Schedule_table");
        jTable3.setModel(DbUtils.resultSetToTableModel(AutoDB_Connect.DB_ResultSet));
        AutoDB_Connect.DB_ResultSet = autoSqlQuery.executeQuery("SELECT * FROM garmentsystem.r_Cutting_Schedule_table");
        jTable1.setModel(DbUtils.resultSetToTableModel(AutoDB_Connect.DB_ResultSet));        
        
        
   
    }
  
    
    
    public void TextBoxClearCut(){
       jTextField28.setText("");
      // jComboBox5.setSelectedItem(null);
       //datePicker7.setText("");
      // datePicker8.setText("");
       //styleCombo.setSelectedItem(null);
       //jComboBox2.setSelectedItem(null);
       //jComboBox1.setSelectedItem(null);
       jTextField1.setText("");
       jTextField29.setText("");
       jTextField32.setText("");
       jTextField26.setText("");
       //jComboBox3.setSelectedItem(null);
       jTextField30.setText("");
       jLabel1.setText("");
    
    }
    
    
     private void FillComboMaterial()
    {
        try
        {
            AutoDB_Connect.DB_ResultSet = autoSqlQuery.executeQuery("SELECT * FROM garmentsystem.Raw_Materials");
            
            while(AutoDB_Connect.DB_ResultSet.next())
            {
                String matid = AutoDB_Connect.DB_ResultSet.getString("Material_id");
                jComboBox2.addItem(matid);
                                       
             
            }
        }
        catch (SQLException ex)
        {
            System.out.println(ex);
        }
    }
    
    private void generate_cdi(){
    AutoIdGenerator aid = new AutoIdGenerator();
    jTextField28.setText(aid.generate("CUT-SHI",Integer.toString(MainWindow.userid)));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        myGroup = new javax.swing.ButtonGroup();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        jPanel9 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jLabel33 = new javax.swing.JLabel();
        jButton5 = new javax.swing.JButton();
        jLabel34 = new javax.swing.JLabel();
        jLabel35 = new javax.swing.JLabel();
        jTextField26 = new javax.swing.JTextField();
        jLabel36 = new javax.swing.JLabel();
        jTextField28 = new javax.swing.JTextField();
        jLabel37 = new javax.swing.JLabel();
        jTextField29 = new javax.swing.JTextField();
        jLabel38 = new javax.swing.JLabel();
        jPanel10 = new javax.swing.JPanel();
        jLabel39 = new javax.swing.JLabel();
        DatePickerSettings dateSettings = new DatePickerSettings();
        dateSettings.setFormatForDatesCommonEra("yyyy-MM-dd");
        dateSettings.setFormatForDatesBeforeCommonEra("uuuu-MM-dd");
        datePicker7 = new com.github.lgooddatepicker.components.DatePicker(dateSettings);
        jLabel40 = new javax.swing.JLabel();
        DatePickerSettings dateSettings1 = new DatePickerSettings();
        dateSettings1.setFormatForDatesCommonEra("yyyy-MM-dd");
        dateSettings1.setFormatForDatesBeforeCommonEra("yyyy-MM-dd");
        datePicker8 = new com.github.lgooddatepicker.components.DatePicker(dateSettings1);
        jLabel41 = new javax.swing.JLabel();
        jTextField30 = new javax.swing.JTextField();
        jLabel42 = new javax.swing.JLabel();
        jTextField31 = new javax.swing.JTextField();
        jLabel43 = new javax.swing.JLabel();
        jComboBox2 = new javax.swing.JComboBox<>();
        jPanel11 = new javax.swing.JPanel();
        jLabel44 = new javax.swing.JLabel();
        jTextField32 = new javax.swing.JTextField();
        jLabel45 = new javax.swing.JLabel();
        jLabel46 = new javax.swing.JLabel();
        jTextField33 = new javax.swing.JTextField();
        jLabel47 = new javax.swing.JLabel();
        jLabel48 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel49 = new javax.swing.JLabel();
        jTextField34 = new javax.swing.JTextField();
        jLabel50 = new javax.swing.JLabel();
        jTextField35 = new javax.swing.JTextField();
        jLabel51 = new javax.swing.JLabel();
        styleCombo = new javax.swing.JComboBox<>();
        jComboBox1 = new javax.swing.JComboBox<>();
        jTextField1 = new javax.swing.JTextField();
        jButton3 = new javax.swing.JButton();
        jComboBox3 = new javax.swing.JComboBox<>();
        jComboBox5 = new javax.swing.JComboBox<>();
        jButton2 = new javax.swing.JButton();
        jButton10 = new javax.swing.JButton();
        jButton11 = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jPanel12 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        DatePickerSettings dateSettings2 = new DatePickerSettings();
        dateSettings2.setFormatForDatesCommonEra("yyyy-MM-dd");
        dateSettings2.setFormatForDatesBeforeCommonEra("yyyy-MM-dd");
        datePicker2 = new com.github.lgooddatepicker.components.DatePicker(dateSettings2);
        jLabel4 = new javax.swing.JLabel();
        DatePickerSettings dateSettings3 = new DatePickerSettings();
        dateSettings3.setFormatForDatesCommonEra("yyyy-MM-dd");
        dateSettings3.setFormatForDatesBeforeCommonEra("yyyy-MM-dd");
        datePicker4 = new com.github.lgooddatepicker.components.DatePicker(dateSettings3);
        jLabel5 = new javax.swing.JLabel();
        jTextField7 = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTable3 = new javax.swing.JTable();
        jLabel56 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jComboBox4 = new javax.swing.JComboBox<>();
        jButton1 = new javax.swing.JButton();
        jComboBox6 = new javax.swing.JComboBox<>();
        jComboBox7 = new javax.swing.JComboBox<>();
        jPanel6 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jTextField9 = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jTextField11 = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();
        jTextField12 = new javax.swing.JTextField();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jButton6 = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        jLabel52 = new javax.swing.JLabel();
        jTextField22 = new javax.swing.JTextField();
        jLabel53 = new javax.swing.JLabel();
        jTextField23 = new javax.swing.JTextField();
        jLabel54 = new javax.swing.JLabel();
        jTextField24 = new javax.swing.JTextField();
        jLabel55 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jComboBox8 = new javax.swing.JComboBox<>();
        jComboBox9 = new javax.swing.JComboBox<>();
        jComboBox10 = new javax.swing.JComboBox<>();
        DatePickerSettings dateSettings7 = new DatePickerSettings();
        dateSettings7.setFormatForDatesCommonEra("yyyy-MM-dd");
        dateSettings7.setFormatForDatesBeforeCommonEra("yyyy-MM-dd");
        datePicker1 = new com.github.lgooddatepicker.components.DatePicker(dateSettings7);
        DatePickerSettings dateSettings8 = new DatePickerSettings();
        dateSettings8.setFormatForDatesCommonEra("yyyy-MM-dd");
        dateSettings8.setFormatForDatesBeforeCommonEra("yyyy-MM-dd");
        datePicker6 = new com.github.lgooddatepicker.components.DatePicker(dateSettings8);
        jPanel4 = new javax.swing.JPanel();
        jLabel15 = new javax.swing.JLabel();
        jTextField8 = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        DatePickerSettings dateSettings4 = new DatePickerSettings();
        dateSettings4.setFormatForDatesCommonEra("yyyy-MM-dd");
        dateSettings4.setFormatForDatesBeforeCommonEra("yyyy-MM-dd");
        datePicker3 = new com.github.lgooddatepicker.components.DatePicker(dateSettings4);
        jLabel21 = new javax.swing.JLabel();
        DatePickerSettings dateSettings5 = new DatePickerSettings();
        dateSettings5.setFormatForDatesCommonEra("yyyy-MM-dd");
        dateSettings5.setFormatForDatesBeforeCommonEra("yyyy-MM-dd");
        datePicker5 = new com.github.lgooddatepicker.components.DatePicker(dateSettings5);
        jComboBox11 = new javax.swing.JComboBox<>();
        jLabel22 = new javax.swing.JLabel();
        jLabel57 = new javax.swing.JLabel();
        jComboBox12 = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jButton4 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jButton9 = new javax.swing.JButton();
        jLabel13 = new javax.swing.JLabel();
        jComboBox13 = new javax.swing.JComboBox<>();

        setResizable(true);
        setTitle("Cutting Schedule");
        setMaximumSize(new java.awt.Dimension(1365, 620));
        setMinimumSize(new java.awt.Dimension(1365, 620));
        setPreferredSize(new java.awt.Dimension(1365, 620));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTabbedPane1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel9.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel9.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jPanel9.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel8.setText("Style ID");
        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jPanel9.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 90, -1, -1));

        jLabel33.setText("No of Lines");
        jLabel33.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jPanel9.add(jLabel33, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 380, -1, -1));

        jButton5.setText("ADD schedule");
        jButton5.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        jPanel9.add(jButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(1050, 210, -1, -1));

        jLabel34.setText("No of Labourers");
        jLabel34.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jPanel9.add(jLabel34, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 320, -1, -1));

        jLabel35.setText("Room No");
        jLabel35.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jPanel9.add(jLabel35, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 350, -1, -1));
        jPanel9.add(jTextField26, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 320, 150, -1));

        jLabel36.setText("Schedule ID");
        jLabel36.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jPanel9.add(jLabel36, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 30, -1, -1));

        jTextField28.setEditable(false);
        jPanel9.add(jTextField28, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 30, 150, -1));

        jLabel37.setText("Quantity");
        jLabel37.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jPanel9.add(jLabel37, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 180, -1, -1));
        jPanel9.add(jTextField29, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 180, 150, -1));

        jLabel38.setText("Colour");
        jLabel38.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jPanel9.add(jLabel38, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 120, -1, -1));

        jPanel10.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Days", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 12))); // NOI18N
        jPanel10.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jPanel10.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel39.setText("End Date");
        jLabel39.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jPanel10.add(jLabel39, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 130, -1, -1));

        datePicker7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                datePicker7MouseExited(evt);
            }
        });
        jPanel10.add(datePicker7, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 90, -1, -1));

        jLabel40.setText("Start Date");
        jLabel40.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jPanel10.add(jLabel40, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 100, -1, -1));
        jPanel10.add(datePicker8, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 120, -1, -1));

        jLabel41.setText("No of Minutes per Sample");
        jLabel41.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jPanel10.add(jLabel41, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 30, -1, -1));

        jTextField30.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jTextField30MouseExited(evt);
            }
        });
        jPanel10.add(jTextField30, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 30, 140, -1));

        jLabel42.setText("Total No of Days");
        jLabel42.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jPanel10.add(jLabel42, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 60, -1, -1));

        jTextField31.setEditable(false);
        jTextField31.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField31ActionPerformed(evt);
            }
        });
        jPanel10.add(jTextField31, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 60, 140, -1));

        jPanel9.add(jPanel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 80, 390, 180));

        jLabel43.setText("Size");
        jLabel43.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jPanel9.add(jLabel43, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 150, -1, -1));

        jComboBox2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jComboBox2MouseClicked(evt);
            }
        });
        jComboBox2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox2ActionPerformed(evt);
            }
        });
        jPanel9.add(jComboBox2, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 210, 150, -1));

        jPanel11.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Availability", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 12))); // NOI18N
        jPanel11.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel44.setText("Length per sample");
        jLabel44.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jPanel11.add(jLabel44, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 40, -1, -1));

        jTextField32.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jTextField32MouseExited(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jTextField32MouseReleased(evt);
            }
        });
        jPanel11.add(jTextField32, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 40, 130, -1));

        jLabel45.setText("meters");
        jPanel11.add(jLabel45, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 40, -1, -1));

        jLabel46.setText("Total length needed");
        jLabel46.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jPanel11.add(jLabel46, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 80, -1, -1));

        jTextField33.setEditable(false);
        jTextField33.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                jTextField33PropertyChange(evt);
            }
        });
        jPanel11.add(jTextField33, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 80, 130, -1));

        jLabel47.setText("meters");
        jPanel11.add(jLabel47, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 80, -1, -1));

        jLabel48.setText("One roll has 100 m");
        jLabel48.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel48.setOpaque(true);
        jPanel11.add(jLabel48, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 140, -1, -1));
        jPanel11.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 110, 150, 20));

        jPanel9.add(jPanel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 270, 390, 170));

        jLabel49.setText("Material ID");
        jLabel49.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jPanel9.add(jLabel49, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 210, -1, -1));

        jTextField34.setEditable(false);
        jPanel9.add(jTextField34, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 150, 150, -1));

        jLabel50.setText("Material Name");
        jLabel50.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jPanel9.add(jLabel50, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 250, -1, -1));

        jTextField35.setEditable(false);
        jPanel9.add(jTextField35, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 240, 150, -1));

        jLabel51.setText("Supervisor ");
        jLabel51.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jPanel9.add(jLabel51, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 280, -1, -1));

        styleCombo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                styleComboMouseClicked(evt);
            }
        });
        jPanel9.add(styleCombo, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 90, 150, -1));

        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });
        jPanel9.add(jComboBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 280, 150, -1));

        jTextField1.setEditable(false);
        jPanel9.add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 120, 150, -1));

        jButton3.setText("View Table");
        jButton3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel9.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(1050, 290, 120, -1));

        jComboBox3.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "-select-", "1", "2", "3", "4", "5", "6", " " }));
        jComboBox3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox3ActionPerformed(evt);
            }
        });
        jPanel9.add(jComboBox3, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 380, 150, -1));

        jComboBox5.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "-select-", "C001", "C002", "C003", "C004", "C005" }));
        jComboBox5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox5ActionPerformed(evt);
            }
        });
        jPanel9.add(jComboBox5, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 350, 150, -1));

        jButton2.setText("Demo");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel9.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(1070, 390, -1, -1));

        jButton10.setText("Select");
        jButton10.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton10ActionPerformed(evt);
            }
        });
        jPanel9.add(jButton10, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 210, 80, -1));

        jButton11.setText("Select");
        jButton11.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton11ActionPerformed(evt);
            }
        });
        jPanel9.add(jButton11, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 90, 80, -1));

        jPanel5.add(jPanel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 20, 1260, 520));

        jPanel1.add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        jTabbedPane1.addTab("ADD Cutting schedule", jPanel1);

        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel12.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel12.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setText("Start Date");
        jLabel3.setEnabled(false);
        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jPanel12.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 70, -1, -1));

        datePicker2.setEnabled(false);
        jPanel12.add(datePicker2, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 70, -1, -1));

        jLabel4.setText("End Date");
        jLabel4.setEnabled(false);
        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jPanel12.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 100, -1, -1));

        datePicker4.setEnabled(false);
        jPanel12.add(datePicker4, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 100, -1, -1));

        jLabel5.setText("Schedule ID");
        jLabel5.setEnabled(false);
        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jPanel12.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 40, -1, -1));

        jTextField7.setEnabled(false);
        jPanel12.add(jTextField7, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 40, 140, -1));

        jLabel6.setText("Room No");
        jLabel6.setEnabled(false);
        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jPanel12.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 130, -1, -1));

        jTable3.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jTable3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable3MouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(jTable3);

        jPanel12.add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 210, 810, 250));

        jLabel56.setText("Supervisor ID");
        jLabel56.setEnabled(false);
        jLabel56.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jPanel12.add(jLabel56, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 160, -1, -1));

        jLabel2.setText("Search By");
        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jPanel12.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 50, -1, -1));

        jComboBox4.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "-Select-", "Schedule ID", "Start Date", "End Date", "Room No", "Supervisor ID" }));
        jComboBox4.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jComboBox4ItemStateChanged(evt);
            }
        });
        jComboBox4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jComboBox4MouseClicked(evt);
            }
        });
        jPanel12.add(jComboBox4, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 50, 110, -1));

        jButton1.setText("Search");
        jButton1.setEnabled(false);
        jButton1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel12.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 90, -1, -1));

        jComboBox6.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "-select-", "C001", "C002", "C003", "C004", "C005" }));
        jComboBox6.setEnabled(false);
        jComboBox6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox6ActionPerformed(evt);
            }
        });
        jPanel12.add(jComboBox6, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 130, 140, -1));

        jComboBox7.setEnabled(false);
        jComboBox7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox7ActionPerformed(evt);
            }
        });
        jPanel12.add(jComboBox7, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 160, 140, -1));

        jPanel3.add(jPanel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 40, 830, 470));

        jPanel6.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel6.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel9.setText("Schedule ID");
        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jPanel6.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 20, 80, -1));
        jPanel6.add(jTextField9, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 50, 170, -1));

        jLabel10.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel6.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 20, 170, 20));

        jLabel11.setText("Style  ID");
        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jPanel6.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 50, -1, -1));

        jLabel14.setText("Start Date");
        jLabel14.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jPanel6.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 200, -1, -1));

        jLabel17.setText("Minutes per sample");
        jLabel17.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jPanel6.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 260, -1, -1));

        jTextField11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField11ActionPerformed(evt);
            }
        });
        jPanel6.add(jTextField11, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 260, 170, -1));

        jLabel18.setText("No of Labourers");
        jLabel18.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jPanel6.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 290, -1, -1));
        jPanel6.add(jTextField12, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 290, 170, -1));

        jLabel19.setText("Room No");
        jLabel19.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jPanel6.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 320, -1, -1));

        jLabel20.setText("No of Lines");
        jLabel20.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jPanel6.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 350, -1, -1));

        jButton6.setText("Edit");
        jButton6.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        jPanel6.add(jButton6, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 430, -1, -1));

        jButton8.setText("Delete");
        jButton8.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });
        jPanel6.add(jButton8, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 430, -1, -1));

        jLabel52.setText("Material ID");
        jLabel52.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jPanel6.add(jLabel52, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 80, -1, -1));
        jPanel6.add(jTextField22, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 80, 170, -1));

        jLabel53.setText("Length per sample");
        jLabel53.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jPanel6.add(jLabel53, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 390, -1, -1));
        jPanel6.add(jTextField23, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 380, 170, -1));

        jLabel54.setText("Quantity");
        jLabel54.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jPanel6.add(jLabel54, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 140, -1, -1));
        jPanel6.add(jTextField24, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 140, 170, -1));

        jLabel55.setText("Colour");
        jLabel55.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jPanel6.add(jLabel55, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 170, -1, -1));

        jTextField2.setEditable(false);
        jTextField2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField2ActionPerformed(evt);
            }
        });
        jPanel6.add(jTextField2, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 170, 170, -1));

        jLabel7.setText("End Date");
        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jPanel6.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 230, -1, -1));

        jLabel12.setText("Supervisor");
        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jPanel6.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 110, 90, -1));

        jComboBox8.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "-select-", "C001", "C002", "C003", "C004", "C005" }));
        jPanel6.add(jComboBox8, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 320, 170, -1));

        jComboBox9.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "-select-", "1", "2", "3", "4", "5", "6", " " }));
        jPanel6.add(jComboBox9, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 350, 170, -1));

        jPanel6.add(jComboBox10, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 110, 170, -1));
        jPanel6.add(datePicker1, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 200, 170, -1));
        jPanel6.add(datePicker6, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 230, 170, -1));

        jPanel3.add(jPanel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(850, 40, 480, 470));

        jTabbedPane1.addTab("Search & Update ||  Delete", jPanel3);

        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel15.setText("Schedule ID");
        jLabel15.setEnabled(false);
        jLabel15.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jPanel4.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 50, -1, -1));

        jTextField8.setEditable(false);
        jTextField8.setEnabled(false);
        jTextField8.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTextField8MouseClicked(evt);
            }
        });
        jPanel4.add(jTextField8, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 50, 140, -1));

        jLabel16.setText("Start Date");
        jLabel16.setEnabled(false);
        jLabel16.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jPanel4.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 80, -1, -1));

        datePicker3.setEnabled(false);
        datePicker3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                datePicker3MouseClicked(evt);
            }
        });
        jPanel4.add(datePicker3, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 80, -1, -1));

        jLabel21.setText("End Date");
        jLabel21.setEnabled(false);
        jLabel21.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jPanel4.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 110, -1, -1));

        datePicker5.setEnabled(false);
        datePicker5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                datePicker5MouseClicked(evt);
            }
        });
        jPanel4.add(datePicker5, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 110, -1, -1));

        jComboBox11.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "-select-", "C001", "C002", "C003", "C004", "C005" }));
        jComboBox11.setEnabled(false);
        jComboBox11.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jComboBox11MouseClicked(evt);
            }
        });
        jComboBox11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox11ActionPerformed(evt);
            }
        });
        jPanel4.add(jComboBox11, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 140, 140, -1));

        jLabel22.setText("Room No");
        jLabel22.setEnabled(false);
        jLabel22.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jPanel4.add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 140, -1, -1));

        jLabel57.setText("Supervisor ID");
        jLabel57.setEnabled(false);
        jLabel57.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jPanel4.add(jLabel57, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 170, -1, -1));

        jComboBox12.setEnabled(false);
        jComboBox12.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jComboBox12MouseClicked(evt);
            }
        });
        jComboBox12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox12ActionPerformed(evt);
            }
        });
        jPanel4.add(jComboBox12, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 170, 140, -1));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        jPanel4.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 210, 680, -1));

        jButton4.setText("Search");
        jButton4.setEnabled(false);
        jButton4.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        jPanel4.add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 100, -1, -1));

        jButton7.setText("Full report");
        jButton7.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });
        jPanel4.add(jButton7, new org.netbeans.lib.awtextra.AbsoluteConstraints(940, 100, -1, -1));

        jButton9.setText("Filtered report");
        jButton9.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton9ActionPerformed(evt);
            }
        });
        jPanel4.add(jButton9, new org.netbeans.lib.awtextra.AbsoluteConstraints(930, 140, -1, -1));

        jLabel13.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel13.setText("Search By");
        jPanel4.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 60, -1, -1));

        jComboBox13.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "-Select-", "Schedule ID", "Start Date", "End Date", "Room No", "Supervisor ID" }));
        jComboBox13.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jComboBox13ItemStateChanged(evt);
            }
        });
        jComboBox13.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jComboBox13MouseClicked(evt);
            }
        });
        jPanel4.add(jComboBox13, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 60, 110, -1));

        jTabbedPane1.addTab("Reports", jPanel4);

        getContentPane().add(jTabbedPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1350, 590));

        getAccessibleContext().setAccessibleName("");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    
    
    public void textClear(){
      jTextField1.setText("");
      jTextField34.setText("");
      jTextField29.setText("");
      jTextField35.setText("");
      jTextField26.setText("");
      jTextField30.setText("");
      jTextField31.setText("");
      jTextField32.setText("");
      jTextField33.setText("");
      datePicker7.setText("");
      datePicker8.setText("");
      jLabel1.setText("");
      generate_cdi();
    
    }
    
    
    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
      
        
            String scheduleID=jTextField28.getText();
            String RoomNo=(String)jComboBox5.getSelectedItem();
            String startDate=datePicker7.getText();
            String EndDate=datePicker8.getText();
            String size=jTextField34.getText();
            String styleNo=(String) styleCombo.getSelectedItem();
            String materialID=(String) jComboBox2.getSelectedItem();
            String matname=jTextField35.getText();
            String supervisorID=(String) jComboBox1.getSelectedItem();
            String color=jTextField1.getText();
            String qty=jTextField29.getText();
            String length=jTextField32.getText();
            String totlength=jTextField33.getText();
            String totdays=jTextField31.getText();
            String lab=jTextField26.getText();
            String minutes=jTextField30.getText();
            String lines=jComboBox3.getSelectedItem().toString();
            
             System.err.println(startDate);
        
        
      
     
        if(color.isEmpty()||size.isEmpty()||qty.isEmpty()||matname.isEmpty()||RoomNo.equals("-select-")||lines.equals("-select-")||lab.isEmpty()||minutes.isEmpty()||totdays.isEmpty()||length.isEmpty())
        {
            
            JOptionPane.showMessageDialog(null, "WARNING FIELDS ARE EMPTY","Failure",JOptionPane.ERROR_MESSAGE);
        }    
        else{

        try{
               
            if(validation.checkDate(startDate,EndDate)&& validation.isDigit(lab)&&validation.isDigit(lines)&&validation.isDigit(minutes)&&validation.isDigit(length)&&validation.isDigit(qty)) {
                    
                String availability="";
                String matid=(String)jComboBox2.getSelectedItem();
            
                 AutoDB_Connect.DB_ResultSet = autoSqlQuery.executeAutoSearchAll("Raw_Materials", "Material_id", matid);
                 AutoDB_Connect.DB_ResultSet.next();
                 int rolls =Integer.valueOf(AutoDB_Connect.DB_ResultSet.getString("Material_qty"));
                 int need=Integer.valueOf(jTextField33.getText())/100;
                 System.out.println("condition");

                 if(rolls>=need)
                 {
                     System.out.println("condition1");
                     availability="Available";
                 }
                 else{
                     availability="Not Available";
                     System.out.println("condition2");
                 }
             
            

            boolean x = autoSqlQuery.execute("INSERT INTO `garmentsystem`.`r_Cutting_Schedule_table`\n" +
     "(`Shedule_ID`,\n" +
     "`Style_ID`,\n" +
     "`Material_ID`,\n" +
     "`Supervisor_ID`,\n" +
     "`No_of_Labourers`,\n" +
     "`Room_No`,\n" +
     "`No_of_Lines`,\n" +
     "`Minutes_per_Sample`,\n" +
     "`Start_Date`,\n" +
     "`End_Date`,\n" +
     "`Length_per_Sample`,\n" +
     "`Stock_Availability`,\n" +
     "`Quantity`,\n"+
     "`Colour`)\n"+
     "VALUES\n" +
     "('"+scheduleID+"',\n" +
     "'"+styleNo+"',\n" +
     "'"+materialID+"',\n" +
     "'"+supervisorID+"',\n" +
     "'"+lab+"',\n" +
     "'"+RoomNo+"',\n" +
     "'"+lines+"',\n" +
     "'"+minutes+"',\n" +
     "'"+startDate+"',\n" +
     "'"+EndDate+"',\n" +
     "'"+length+"',\n" +
     "'"+availability+"',\n"+
     "'"+qty+"',\n"+
     "'"+color+"');");

            JOptionPane.showMessageDialog(null,"Successful");
            textClear();
               
            
         }
        }
        
    
         catch(Exception e){
                System.out.println(e);
          }

                
        }    
              
    }//GEN-LAST:event_jButton5ActionPerformed

    private void FillCombo()
    {
        try
        {
            AutoDB_Connect.DB_ResultSet = autoSqlQuery.executeQuery("SELECT * FROM garmentsystem.T_Design_table");
            
            while(AutoDB_Connect.DB_ResultSet.next())
            {
                String id = AutoDB_Connect.DB_ResultSet.getString("StyleId");
                styleCombo.addItem(id);
                
               
            }
        }
        catch (SQLException ex)
        {
            System.out.println(ex);
        }
    }
        private void FillComboSupervisor()
    {
        try
        {
            AutoDB_Connect.DB_ResultSet = autoSqlQuery.executeQuery("SELECT * FROM garmentsystem.emp_table WHERE depid='5' ");
            
            while(AutoDB_Connect.DB_ResultSet.next())
            {
                String id = AutoDB_Connect.DB_ResultSet.getString("f_name");
                jComboBox1.addItem(id);
                
               
            }
        }
        catch (SQLException ex)
        {
            System.out.println(ex);
        }
        
    }
        private void FillComboSupervisor2()
    {
        try
        {
            AutoDB_Connect.DB_ResultSet = autoSqlQuery.executeQuery("SELECT * FROM garmentsystem.emp_table WHERE depid='5' ");
            
            while(AutoDB_Connect.DB_ResultSet.next())
            {
                String id = AutoDB_Connect.DB_ResultSet.getString("f_name");
                jComboBox10.addItem(id);
                jComboBox7.addItem(id);
                jComboBox12.addItem(id);
               
            }
        }
        catch (SQLException ex)
        {
            System.out.println(ex);
        }
        
    }
    
    
    private void jTextField31ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField31ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField31ActionPerformed

    private void jTextField11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField11ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField11ActionPerformed

    private void styleComboMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_styleComboMouseClicked
        
        //String size="";
        //String color="";
        String style = styleCombo.getSelectedItem().toString();
        AutoDB_Connect.DB_ResultSet = autoSqlQuery.executeQuery("SELECT Size,Color FROM garmentsystem.T_Design_table WHERE StyleId ='"+style+"'");
       
        try {
            
            AutoDB_Connect.DB_ResultSet.next();
            String size=AutoDB_Connect.DB_ResultSet.getString("Size");
            String color=AutoDB_Connect.DB_ResultSet.getString("color");
            jTextField34.setText(size);
            jTextField1.setText(color);
        } catch (SQLException ex) {
            Logger.getLogger(CuttingSchedule.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }//GEN-LAST:event_styleComboMouseClicked

    private void jComboBox2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jComboBox2MouseClicked
        //String name="";
        String matid = jComboBox2.getSelectedItem().toString();
        AutoDB_Connect.DB_ResultSet = autoSqlQuery.executeQuery("SELECT Material_Name FROM garmentsystem.Raw_Materials WHERE Material_id ='"+matid+"'");
         try {
            
            AutoDB_Connect.DB_ResultSet.next();
            String name=AutoDB_Connect.DB_ResultSet.getString("Material_Name");
            jTextField35.setText(name);
            
        } catch (SQLException ex) {
            Logger.getLogger(CuttingSchedule.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }//GEN-LAST:event_jComboBox2MouseClicked

    private void jTextField30MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTextField30MouseExited
        try{
        int qty=Integer.valueOf(jTextField29.getText());
        int sample=Integer.valueOf(jTextField30.getText());
        int days=(qty*sample)/60;
        if(days<24)
            jTextField31.setText("1");
        else
            jTextField31.setText( Integer.toString(days/24));
        }
        catch(Exception e){
            System.out.println(e);
        }
        
    }//GEN-LAST:event_jTextField30MouseExited

    private void datePicker7MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_datePicker7MouseExited
        
    }//GEN-LAST:event_datePicker7MouseExited

    private void jTextField32MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTextField32MouseExited
      
        try{
        int qty=Integer.valueOf(jTextField29.getText());
        int sample=Integer.valueOf(jTextField32.getText());
        int width=qty*sample;
        jTextField33.setText( Integer.toString(width));
                              
        }
        catch(NumberFormatException e){
            System.out.println(e);
        }       
        
            String matid=(String)jComboBox2.getSelectedItem();
           
            try{
           AutoDB_Connect.DB_ResultSet = autoSqlQuery.executeAutoSearchAll("Raw_Materials", "Material_id", matid);
            AutoDB_Connect.DB_ResultSet.next();
           String x =AutoDB_Connect.DB_ResultSet.getString("Material_qty");
            
            int roll =Integer.valueOf(x);
           
            int need=Integer.valueOf(jTextField33.getText())/100;
            
            
            if(roll>=need)
            {
                jLabel1.setForeground(Color.blue);
                jLabel1.setText("Available");
            }
            else{
                jLabel1.setForeground(Color.blue);
                jLabel1.setText("Not Available");
            }
        }
            catch(NumberFormatException | SQLException e){
                System.out.println(e);
            }
        
            
    }//GEN-LAST:event_jTextField32MouseExited
  
    
   
    
    
    private void jTextField33PropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_jTextField33PropertyChange
        
    }//GEN-LAST:event_jTextField33PropertyChange

    private void jTextField32MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTextField32MouseReleased
    
    }//GEN-LAST:event_jTextField32MouseReleased

    private void jComboBox4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jComboBox4MouseClicked
       
    }//GEN-LAST:event_jComboBox4MouseClicked

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        search();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        View_table vw = new View_table();
        vw.setVisible(true);
        
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jTable3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable3MouseClicked
        try{
        int r=jTable3.getSelectedRow();
        String schid=jTable3.getValueAt(r, 0).toString();
        String styleID=jTable3.getValueAt(r, 1).toString();
        String MaterialID=jTable3.getValueAt(r, 2).toString();
        String supervisorID=jTable3.getValueAt(r, 3).toString();
        String Qty=jTable3.getValueAt(r, 12).toString();
        String Colour=jTable3.getValueAt(r, 13).toString();
        String daysPerSample=jTable3.getValueAt(r, 7).toString();
        String RoomNo=jTable3.getValueAt(r, 5).toString();
        String noOfLabourers=jTable3.getValueAt(r, 4).toString();
        String noOfLines=jTable3.getValueAt(r, 6).toString();
        String width=jTable3.getValueAt(r, 10).toString();
        String Startdate=jTable3.getValueAt(r,8).toString();
        String Enddate=jTable3.getValueAt(r, 9).toString();
       // System.err.print(supervisorID);
        jLabel10.setText(schid);
        jTextField9.setText(styleID);
        jTextField22.setText(MaterialID);
        jComboBox10.setSelectedItem(supervisorID);
        jTextField11.setText(daysPerSample);
        jTextField12.setText(noOfLabourers);
        jComboBox8.setSelectedItem(RoomNo);
        jComboBox9.setSelectedItem(noOfLines);
        jTextField23.setText(width);
        jTextField24.setText(Qty);
        jTextField2.setText(Colour);
        LocalDate Stdate = LocalDate.parse(Startdate);
        datePicker1.setDate(Stdate);
        LocalDate EndDate = LocalDate.parse(Enddate);
        datePicker6.setDate(EndDate);
      
    }catch(Exception e)
    {
        System.out.println(e);
    }
        
    }//GEN-LAST:event_jTable3MouseClicked

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
          int reply = JOptionPane.showConfirmDialog(null, 
                 "Are you sure you want to Delete?", "Delete?", 
                            JOptionPane.YES_NO_OPTION);
        
          if (reply == JOptionPane.YES_OPTION){

        String id = jLabel10.getText();
        
        boolean x = autoSqlQuery.execute("DELETE FROM `garmentsystem`.`r_Cutting_Schedule_table`\n" +
"WHERE Shedule_ID='"+id+"';");
       if(x==true)
            JOptionPane.showMessageDialog(null,"Successfully Deleted");
          }
    }//GEN-LAST:event_jButton8ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        
              
          
        String shid = jLabel10.getText();
        String stID=jTextField9.getText();
        String matID=jTextField22.getText();
        String supID=jComboBox10.getSelectedItem().toString();
        String days=jTextField11.getText();
        String labour=jTextField12.getText();
        String roomNo=jComboBox8.getSelectedItem().toString();
        String Lines=jComboBox9.getSelectedItem().toString();
        String width=jTextField23.getText();
        String qty=jTextField24.getText();
        String color=jTextField2.getText();
        String startDate=datePicker1.getText();
        String EndDate=datePicker6.getText();
        String availability="";
        
       
        if(stID.isEmpty()||matID.isEmpty()||width.isEmpty()|color.isEmpty())
        {
            
            JOptionPane.showMessageDialog(null, "WARNING FIELDS ARE EMPTY","Failure",JOptionPane.ERROR_MESSAGE);
            
        }
        else{
            
            
                try
                {

                    if(validation.checkDate(startDate, EndDate) && validation.isDigit(labour) && validation.isDigit(days) && validation.isDigit(Lines) && validation.isDigit(qty))
                    {
                        
                        Double need=(Double.parseDouble(qty)*Double.parseDouble(width))/100;
        
          try{
           AutoDB_Connect.DB_ResultSet = autoSqlQuery.executeAutoSearchAll("Raw_Materials", "Material_id", matID);
            AutoDB_Connect.DB_ResultSet.next();
           String x =AutoDB_Connect.DB_ResultSet.getString("Material_qty");
            
            int roll =Integer.valueOf(x);
           
            
            
            if(roll>=need)
            {
                availability="available";
            }
            else{
                availability="Not available";
            }
        }
            catch(NumberFormatException | SQLException e){
                System.out.println(e);
            }
            int reply = JOptionPane.showConfirmDialog(null, 
                 "Are you sure you want to Update?", "Update?", 
                            JOptionPane.YES_NO_OPTION);
        
          if (reply == JOptionPane.YES_OPTION){
          
                 boolean x = autoSqlQuery.execute("UPDATE `garmentsystem`.`r_Cutting_Schedule_table`\n" +
         "SET\n" +
         //"`Shedule_ID` = '"+shid+"',\n" +
         "`Style_ID` = '"+stID+"',\n" +
         "`Material_ID` = '"+matID+"',\n" +
         "`Supervisor_ID` = '"+supID+"',\n" +
         "`No_of_Labourers` = '"+labour+"',\n" +
         "`Room_No` = '"+roomNo+"',\n" +
         "`No_of_Lines` = '"+Lines+"',\n" +
         "`Minutes_per_Sample` = '"+days+"',\n" +
         "`Start_Date` = '"+startDate+"',\n" +
         "`End_Date` = '"+EndDate+"',\n" +
         "`Length_per_Sample` = '"+width+"',\n" +
         "`Stock_Availability` = '"+availability+"',\n" +
         "`Quantity` = '"+qty+"',\n" +
         "`Colour` = '"+color+"'\n" +
         "WHERE `Shedule_ID` = '"+shid+"';");


                    if(x==true)
                    {
                        //EditTableLoad();
                        //TextBoxClear();
                        JOptionPane.showMessageDialog(null, "Successfully updated");
                    }
                }
          }
                }
                catch(Exception ex)
                {
                    System.out.println(ex);
                }
       
         
        }
        
    }//GEN-LAST:event_jButton6ActionPerformed

  
    
    
    private void jComboBox5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox5ActionPerformed
        // TODO add your hand-ling code here:
    }//GEN-LAST:event_jComboBox5ActionPerformed

    private void jTextField2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField2ActionPerformed

    private void jComboBox7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox7ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox7ActionPerformed

    private void jComboBox6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox6ActionPerformed

    private void jComboBox11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox11ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox11ActionPerformed

    private void jComboBox12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox12ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox12ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        
        search2();
        
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jTextField8MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTextField8MouseClicked

        jTextField8.setEnabled(true);
        datePicker3.setEnabled(false);
        datePicker5.setEnabled(false);
        jComboBox11.setEnabled(false);
        jComboBox12.setEnabled(false);
    }//GEN-LAST:event_jTextField8MouseClicked

    private void datePicker3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_datePicker3MouseClicked

        jTextField8.setEnabled(false);
        datePicker3.setEnabled(true);
        datePicker5.setEnabled(false);
        jComboBox11.setEnabled(false);
        jComboBox12.setEnabled(false);
    }//GEN-LAST:event_datePicker3MouseClicked

    private void datePicker5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_datePicker5MouseClicked

        jTextField8.setEnabled(false);
        datePicker3.setEnabled(false);
        datePicker5.setEnabled(true);
        jComboBox11.setEnabled(false);
        jComboBox12.setEnabled(false);
    }//GEN-LAST:event_datePicker5MouseClicked

    private void jComboBox11MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jComboBox11MouseClicked

        jTextField8.setEnabled(false);
        datePicker3.setEnabled(false);
        datePicker5.setEnabled(false);
        jComboBox11.setEnabled(true);
        jComboBox12.setEnabled(false);
    }//GEN-LAST:event_jComboBox11MouseClicked


    
    private void jComboBox12MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jComboBox12MouseClicked

        jTextField8.setEnabled(false);
        datePicker3.setEnabled(false);
        datePicker5.setEnabled(false);
        jComboBox11.setEnabled(false);
        jComboBox12.setEnabled(true);
    }//GEN-LAST:event_jComboBox12MouseClicked

    private void jComboBox3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox3ActionPerformed

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox1ActionPerformed

    private void jComboBox4ItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jComboBox4ItemStateChanged
           String search=jComboBox4.getSelectedItem().toString();
         System.out.println(search);
        if(search.equals("Schedule ID"))
        {
            jLabel5.setEnabled(true);
            jTextField7.setEnabled(true);
            jButton1.setEnabled(true);
            
        }
        
        else if (search.equals("Start Date"))
        {
            jLabel3.setEnabled(true);
            datePicker2.setEnabled(true);
            jButton1.setEnabled(true);
        }
        else if (search=="End Date")
        {
            jLabel4.setEnabled(true);
            datePicker4.setEnabled(true);
            jButton1.setEnabled(true);
        }
        else  if(search=="Room No")
        {
            jLabel6.setEnabled(true);
            jComboBox6.setEnabled(true);
            jButton1.setEnabled(true);
        }    
        else if(search=="Supervisor ID")
        {
            jLabel56.setEnabled(true);
            jComboBox7.setEnabled(true);
            jButton1.setEnabled(true);
        }
        else
            JOptionPane.showMessageDialog(null, "Select a category");
       FillComboSupervisor();
    }//GEN-LAST:event_jComboBox4ItemStateChanged

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
      jTextField1.setText("Blue");
      jTextField34.setText("XL");
      jTextField29.setText("6");
      jTextField35.setText("Fabric");
      jTextField26.setText("44");
      jTextField30.setText("6");
      jTextField31.setText("3");
      jTextField32.setText("776");
      jTextField33.setText("3");
      jComboBox5.setSelectedItem("C004");
      jComboBox3.setSelectedItem("4");
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jComboBox2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox2ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        //String x=System.getProperty("user.dir");
        String FileLocation=System.getProperty("user.dir")+"\\src\\ManufacturingPlanning\\Reports\\report1.jrxml";
        System.err.println(FileLocation);
        //./Reports/ipr.jrxml
        String SQL="SELECT * FROM garmentsystem.r_Cutting_Schedule_table";
        autoReport.Query2Report(FileLocation, SQL); 
    }//GEN-LAST:event_jButton7ActionPerformed

    private void jButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton9ActionPerformed
        String FileLocation=System.getProperty("user.dir")+"\\src\\ManufacturingPlanning\\Reports\\report2.jrxml";
        autoReport.Table2Report(FileLocation, jTable1);
    }//GEN-LAST:event_jButton9ActionPerformed

    private void jComboBox13ItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jComboBox13ItemStateChanged
         String search=jComboBox13.getSelectedItem().toString();
         System.out.println(search);
        if(search.equals("Schedule ID"))
        {
            jLabel15.setEnabled(true);
            jTextField8.setEnabled(true);
            jButton4.setEnabled(true);
            
        }
        
        else if (search.equals("Start Date"))
        {
            jLabel16.setEnabled(true);
            datePicker3.setEnabled(true);
            jButton4.setEnabled(true);
        }
        else if (search=="End Date")
        {
            jLabel21.setEnabled(true);
            datePicker5.setEnabled(true);
            jButton4.setEnabled(true);
        }
        else  if(search=="Room No")
        {
            jLabel22.setEnabled(true);
            jComboBox11.setEnabled(true);
            jButton4.setEnabled(true);
        }    
        else if(search=="Supervisor ID")
        {
            jLabel57.setEnabled(true);
            jComboBox12.setEnabled(true);
            jButton4.setEnabled(true);
        }
        else
            JOptionPane.showMessageDialog(null, "Select a category");
      
    }//GEN-LAST:event_jComboBox13ItemStateChanged

    private void jComboBox13MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jComboBox13MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox13MouseClicked

    private void jButton10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton10ActionPerformed
       
        raw_materials rm=new raw_materials();
        rm.setVisible(true);
        
            
        
    }//GEN-LAST:event_jButton10ActionPerformed

    private void jButton11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton11ActionPerformed
        Style s=new Style();
        s.setVisible(true);
    }//GEN-LAST:event_jButton11ActionPerformed
    
    private void MultileSelectError()
    {
       /* jTextField8;
        datePicker3;
        datePicker5;
        jComboBox11;
        jComboBox12;*/
    }
    
    private void search2() 
    {
        try{
        String search=jComboBox13.getSelectedItem().toString();
        if(search=="Schedule ID")
        {
            String schID=jTextField8.getText();
            AutoDB_Connect.DB_ResultSet = autoSqlQuery.executeQuery("SELECT * FROM garmentsystem.r_Cutting_Schedule_table WHERE Shedule_ID ='"+schID+"'");
            jTable1.setModel(DbUtils.resultSetToTableModel(AutoDB_Connect.DB_ResultSet));  
        }
        else if(search=="Start Date")
        {
            String schID=datePicker3.getText();
            AutoDB_Connect.DB_ResultSet = autoSqlQuery.executeQuery("SELECT * FROM garmentsystem.r_Cutting_Schedule_table WHERE Start_Date ='"+schID+"'");
            jTable1.setModel(DbUtils.resultSetToTableModel(AutoDB_Connect.DB_ResultSet));  
        }
        else if(search=="End Date")
        {
            String schID=datePicker5.getText();
            AutoDB_Connect.DB_ResultSet = autoSqlQuery.executeQuery("SELECT * FROM garmentsystem.r_Cutting_Schedule_table WHERE End_Date ='"+schID+"'");
            jTable1.setModel(DbUtils.resultSetToTableModel(AutoDB_Connect.DB_ResultSet));  
        }
        else if(search=="Room No")
        {
            String schID=jComboBox11.getSelectedItem().toString();
            AutoDB_Connect.DB_ResultSet = autoSqlQuery.executeQuery("SELECT * FROM garmentsystem.r_Cutting_Schedule_table WHERE Room_No ='"+schID+"'");
            jTable1.setModel(DbUtils.resultSetToTableModel(AutoDB_Connect.DB_ResultSet));  
        }
        else if(search=="Supervisor ID")
        {
            String schID=jComboBox12.getSelectedItem().toString();
            AutoDB_Connect.DB_ResultSet = autoSqlQuery.executeQuery("SELECT * FROM garmentsystem.r_Cutting_Schedule_table WHERE Supervisor_ID ='"+schID+"'");
            jTable1.setModel(DbUtils.resultSetToTableModel(AutoDB_Connect.DB_ResultSet));  
        }
        
        }
        catch(Exception e){
            System.out.println(e);
        }
    }


    
    
 
   
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private com.github.lgooddatepicker.components.DatePicker datePicker1;
    private com.github.lgooddatepicker.components.DatePicker datePicker2;
    private com.github.lgooddatepicker.components.DatePicker datePicker3;
    private com.github.lgooddatepicker.components.DatePicker datePicker4;
    private com.github.lgooddatepicker.components.DatePicker datePicker5;
    private com.github.lgooddatepicker.components.DatePicker datePicker6;
    private com.github.lgooddatepicker.components.DatePicker datePicker7;
    private com.github.lgooddatepicker.components.DatePicker datePicker8;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton10;
    private javax.swing.JButton jButton11;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JComboBox<String> jComboBox10;
    private javax.swing.JComboBox<String> jComboBox11;
    private javax.swing.JComboBox<String> jComboBox12;
    private javax.swing.JComboBox<String> jComboBox13;
    public javax.swing.JComboBox<String> jComboBox2;
    private javax.swing.JComboBox<String> jComboBox3;
    private javax.swing.JComboBox<String> jComboBox4;
    private javax.swing.JComboBox<String> jComboBox5;
    private javax.swing.JComboBox<String> jComboBox6;
    private javax.swing.JComboBox<String> jComboBox7;
    private javax.swing.JComboBox<String> jComboBox8;
    private javax.swing.JComboBox<String> jComboBox9;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel37;
    private javax.swing.JLabel jLabel38;
    private javax.swing.JLabel jLabel39;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel40;
    private javax.swing.JLabel jLabel41;
    private javax.swing.JLabel jLabel42;
    private javax.swing.JLabel jLabel43;
    private javax.swing.JLabel jLabel44;
    private javax.swing.JLabel jLabel45;
    private javax.swing.JLabel jLabel46;
    private javax.swing.JLabel jLabel47;
    private javax.swing.JLabel jLabel48;
    private javax.swing.JLabel jLabel49;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel50;
    private javax.swing.JLabel jLabel51;
    private javax.swing.JLabel jLabel52;
    private javax.swing.JLabel jLabel53;
    private javax.swing.JLabel jLabel54;
    private javax.swing.JLabel jLabel55;
    private javax.swing.JLabel jLabel56;
    private javax.swing.JLabel jLabel57;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel12;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable jTable3;
    public javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField11;
    private javax.swing.JTextField jTextField12;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField22;
    private javax.swing.JTextField jTextField23;
    private javax.swing.JTextField jTextField24;
    private javax.swing.JTextField jTextField26;
    private javax.swing.JTextField jTextField28;
    private javax.swing.JTextField jTextField29;
    private javax.swing.JTextField jTextField30;
    private javax.swing.JTextField jTextField31;
    private javax.swing.JTextField jTextField32;
    private javax.swing.JTextField jTextField33;
    public javax.swing.JTextField jTextField34;
    public javax.swing.JTextField jTextField35;
    private javax.swing.JTextField jTextField7;
    private javax.swing.JTextField jTextField8;
    private javax.swing.JTextField jTextField9;
    private javax.swing.ButtonGroup myGroup;
    public javax.swing.JComboBox<String> styleCombo;
    // End of variables declaration//GEN-END:variables

    
    private void EditTableLoad()
    {
        AutoDB_Connect.DB_ResultSet = autoSqlQuery.executeQuery("SELECT * FROM garmentsystem.r_Cutting_Schedule_table");
            jTable3.setModel(DbUtils.resultSetToTableModel(AutoDB_Connect.DB_ResultSet));
    }
    private void search() {
           try{
        String search=jComboBox4.getSelectedItem().toString();
        if(search=="Schedule ID")
        {
            String schID=jTextField7.getText();
            AutoDB_Connect.DB_ResultSet = autoSqlQuery.executeQuery("SELECT * FROM garmentsystem.r_Cutting_Schedule_table WHERE Shedule_ID ='"+schID+"'");
            jTable3.setModel(DbUtils.resultSetToTableModel(AutoDB_Connect.DB_ResultSet));  
        }
        else if(search=="Start Date")
        {
            String schID=datePicker2.getText();
            AutoDB_Connect.DB_ResultSet = autoSqlQuery.executeQuery("SELECT * FROM garmentsystem.r_Cutting_Schedule_table WHERE Start_Date ='"+schID+"'");
            jTable3.setModel(DbUtils.resultSetToTableModel(AutoDB_Connect.DB_ResultSet));  
        }
        else if(search=="End Date")
        {
            String schID=datePicker4.getText();
            AutoDB_Connect.DB_ResultSet = autoSqlQuery.executeQuery("SELECT * FROM garmentsystem.r_Cutting_Schedule_table WHERE End_Date ='"+schID+"'");
            jTable3.setModel(DbUtils.resultSetToTableModel(AutoDB_Connect.DB_ResultSet));  
        }
        else if(search=="Room No")
        {
            String schID=jComboBox6.getSelectedItem().toString();
            AutoDB_Connect.DB_ResultSet = autoSqlQuery.executeQuery("SELECT * FROM garmentsystem.r_Cutting_Schedule_table WHERE Room_No ='"+schID+"'");
            jTable3.setModel(DbUtils.resultSetToTableModel(AutoDB_Connect.DB_ResultSet));  
        }
        else if(search=="Supervisor ID")
        {
            String schID=jComboBox7.getSelectedItem().toString();
            AutoDB_Connect.DB_ResultSet = autoSqlQuery.executeQuery("SELECT * FROM garmentsystem.r_Cutting_Schedule_table WHERE Supervisor_ID ='"+schID+"'");
            jTable3.setModel(DbUtils.resultSetToTableModel(AutoDB_Connect.DB_ResultSet));  
        }
        
        }
        catch(Exception e){
            System.out.println(e);
        }
    }
}
