
package Finance;

import static MainSystem.AutoDB_Connect.DB_connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;




/**
 *
 * @author Dinushka
 */
public class balancesheet1 extends javax.swing.JInternalFrame {

    private static Object DepositTotal;



    /**
     * Creates new form SalesDesignInquiry
     */
    public balancesheet1() {
        initComponents();
        CalFixAssets();
   //     CalcBank();
         CalCash();
         CalcCurrTotal();
         CalcLi();
       
       
        
       
     
    }
     private void CalFixAssets()
 {
         try {
             PreparedStatement statement  =DB_connection.prepareStatement("SELECT SUM(Cost) FROM garmentsystem.F_FIXASSETS;");
             ResultSet  results = statement.executeQuery();
                results.next();
                String sum = results.getString(1);
                System.out.println(sum);
                fixassets.setText(sum);
            }
            
            catch (SQLException ex) 
                
             {
                System.out.println(ex.getMessage());
            }
     }
     
        private void CalcfixTotal()
 {
       float fix = Float.parseFloat(fixassets.getText());
       float Investment = Float.parseFloat(invest.getText());
       float Fixtot = (Investment+fix);
       
       System.out.println(Fixtot);
      F_tot.setText(Double.toString(Fixtot));
     }
        

        
    /**
     *
     */
        
        //----------------clculate Bank--------------------
     /*  public static String D_tot = DepositTotal.getText();
        public static String w_tot = WithdrowTotal.getText();
        public static String R_tot = ReturnTotal.getText();
        
        
        private void CalcBank()
 {
     
     
     
      float D_tot = Float.parseFloat(DepositTotal.getText());
       float w_tot = Float.parseFloat(WithdrowTotal.getText());
       float R_tot = Float.parseFloat(ReturnTotal.getText());
       float bank = (D_tot+w_tot)-R_tot;
       
       System.out.println(bank);
      F_tot.setText(Double.toString(bank));
     } 
        */
     
        
         private void CalCash()
 {
     
         try {
             PreparedStatement statement  =DB_connection.prepareStatement("SELECT SUM(Amount) FROM garmentsystem.CASH_DETAILS;");
             ResultSet  results = statement.executeQuery();
                results.next();
                String sum = results.getString(1);
                System.out.println(sum);
                cashtot.setText(sum);
            }
            
            catch (SQLException ex) 
                
             {
                System.out.println(ex.getMessage());
            }
     }
         

         
     //-----------------stock-----------------    
         /*
              private void stock()
 {
      
        float stock = Float.parseFloat(stocktot.getText());
       
      float goods = (open+Purch+Purchre);

       System.out.println(goods);
      Goods.setText(Double.toString(goods));
     }*/
         
    private void CalcCurrTotal()
 {
      float stock = Float.parseFloat(stocktot.getText());
       float cash = Float.parseFloat(cashtot.getText());
       float debit = Float.parseFloat(deb.getText());
       float bank = Float.parseFloat(Bank.getText());
       
       float Currtot = (stock+debit+cash+bank);
       
       System.out.println(Currtot);
      cuAss_tot.setText(Double.toString(Currtot));
     }  
    
       private void CalcLiaCap()
 {
      float Fund = Float.parseFloat(fund.getText());
       float capital = Float.parseFloat(Capital.getText());
       float RS = Float.parseFloat(ReseAndSup.getText());
       //float bank = Float.parseFloat(Bank.getText());
       
       float CurrLiCap = (Fund+capital+RS);//profit and loss value should be here
       
       System.out.println(CurrLiCap);
      liandcaptot.setText(Double.toString(CurrLiCap));
     }  
 
       
       
           private void CalcNonLiaCap()
 {
      float loan = Float.parseFloat(longloan.getText());
       float other = Float.parseFloat(otherli.getText());
     
       
       float CurrnonLiCap = (loan+other);
       
       System.out.println(CurrnonLiCap);
      NonCurrTot.setText(Double.toString(CurrnonLiCap));
     } 
           
       private void CalcLi()
 {
      float shrtlo = Float.parseFloat(shortloan.getText());
       float others = Float.parseFloat(othercurrloan.getText());
       
       
       float CurrnonLi = (shrtlo+others);
       
       System.out.println(CurrnonLi);
      currli.setText(Double.toString(CurrnonLi));
     } 

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jLabel33 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        fixassets = new javax.swing.JTextField();
        jLabel34 = new javax.swing.JLabel();
        invest = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        F_tot = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        jLabel35 = new javax.swing.JLabel();
        stocktot = new javax.swing.JTextField();
        jLabel32 = new javax.swing.JLabel();
        deb = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        cashtot = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        Bank = new javax.swing.JTextField();
        jLabel19 = new javax.swing.JLabel();
        cuAss_tot = new javax.swing.JTextField();
        jLabel20 = new javax.swing.JLabel();
        jTextField10 = new javax.swing.JTextField();
        jPanel8 = new javax.swing.JPanel();
        jPanel7 = new javax.swing.JPanel();
        jLabel15 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabel36 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jLabel37 = new javax.swing.JLabel();
        fund = new javax.swing.JTextField();
        Capital = new javax.swing.JTextField();
        ReseAndSup = new javax.swing.JTextField();
        jTextField14 = new javax.swing.JTextField();
        liandcaptot = new javax.swing.JTextField();
        jLabel21 = new javax.swing.JLabel();
        jPanel9 = new javax.swing.JPanel();
        jLabel38 = new javax.swing.JLabel();
        jLabel39 = new javax.swing.JLabel();
        jLabel30 = new javax.swing.JLabel();
        jLabel31 = new javax.swing.JLabel();
        longloan = new javax.swing.JTextField();
        otherli = new javax.swing.JTextField();
        NonCurrTot = new javax.swing.JTextField();
        jPanel10 = new javax.swing.JPanel();
        jLabel22 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        shortloan = new javax.swing.JTextField();
        othercurrloan = new javax.swing.JTextField();
        currli = new javax.swing.JTextField();
        jLabel26 = new javax.swing.JLabel();
        jTextField21 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();

        setResizable(true);
        setTitle("Bank Details");
        setMaximumSize(new java.awt.Dimension(1365, 620));
        setMinimumSize(new java.awt.Dimension(1365, 620));
        setPreferredSize(new java.awt.Dimension(1365, 620));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTabbedPane1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel6.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel6.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel3.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel33.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel33.setText("FIX ASSETS");
        jPanel3.add(jLabel33, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, -1));

        jLabel16.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel16.setText("Fix Assets Total Cost");
        jPanel3.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 60, 140, -1));
        jPanel3.add(fixassets, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 60, 180, -1));

        jLabel34.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel34.setText("Invesments");
        jPanel3.add(jLabel34, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 100, -1, -1));

        invest.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                investKeyReleased(evt);
            }
        });
        jPanel3.add(invest, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 100, 180, -1));

        jLabel14.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel14.setText("Total");
        jPanel3.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 170, -1, -1));
        jPanel3.add(F_tot, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 170, 130, -1));

        jPanel6.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 30, 410, 210));

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel9.setText("ASSETS");
        jPanel6.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, -1, -1));

        jPanel4.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel10.setText("CURRENT ASSETS");
        jPanel4.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, -1));

        jLabel35.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel35.setText("Stock");
        jPanel4.add(jLabel35, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 40, -1, -1));
        jPanel4.add(stocktot, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 30, 180, -1));

        jLabel32.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel32.setText("Debitors");
        jPanel4.add(jLabel32, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 70, -1, -1));
        jPanel4.add(deb, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 60, 180, -1));

        jLabel13.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel13.setText("Cash");
        jPanel4.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 100, -1, -1));
        jPanel4.add(cashtot, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 90, 180, -1));

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel12.setText("Bank");
        jPanel4.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 130, -1, -1));
        jPanel4.add(Bank, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 120, 180, -1));

        jLabel19.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel19.setText("Total");
        jPanel4.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 170, -1, -1));

        cuAss_tot.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cuAss_totActionPerformed(evt);
            }
        });
        jPanel4.add(cuAss_tot, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 160, 150, -1));

        jPanel6.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 250, 410, 230));

        jLabel20.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel20.setText("TOTAL ASSETS");
        jPanel6.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 500, -1, -1));
        jPanel6.add(jTextField10, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 500, 140, -1));

        jPanel2.add(jPanel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 430, 530));

        jPanel8.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel8.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel7.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel7.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel15.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel15.setText("ShareHolders Fund");
        jPanel7.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 30, 150, -1));

        jLabel23.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel23.setText("Share Capital");
        jPanel7.add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 60, -1, -1));

        jLabel36.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel36.setText("Reserves And Surplus");
        jPanel7.add(jLabel36, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 90, 160, -1));

        jLabel24.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel24.setText("Profit And Loss");
        jPanel7.add(jLabel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 120, 120, -1));

        jLabel37.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel37.setText("Total");
        jPanel7.add(jLabel37, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 150, -1, -1));

        fund.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                fundKeyReleased(evt);
            }
        });
        jPanel7.add(fund, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 20, 140, -1));

        Capital.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                CapitalKeyReleased(evt);
            }
        });
        jPanel7.add(Capital, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 50, 140, -1));

        ReseAndSup.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                ReseAndSupKeyReleased(evt);
            }
        });
        jPanel7.add(ReseAndSup, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 80, 140, -1));
        jPanel7.add(jTextField14, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 110, 140, -1));
        jPanel7.add(liandcaptot, new org.netbeans.lib.awtextra.AbsoluteConstraints(315, 140, 130, -1));

        jLabel21.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel21.setText("LIABILITIES AND CAPITAL");
        jPanel7.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, -1, -1));

        jPanel8.add(jPanel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 30, 460, 170));

        jPanel9.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel9.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel38.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel38.setText("NON CURRENT LIABILITIES");
        jPanel9.add(jLabel38, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, -1));

        jLabel39.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel39.setText("Long Tearm Loans");
        jPanel9.add(jLabel39, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 30, -1, -1));

        jLabel30.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel30.setText("OtherLong Term Liabilities");
        jPanel9.add(jLabel30, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 60, -1, -1));

        jLabel31.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel31.setText("Total");
        jPanel9.add(jLabel31, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 90, -1, -1));

        longloan.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                longloanKeyReleased(evt);
            }
        });
        jPanel9.add(longloan, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 30, 140, -1));

        otherli.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                otherliKeyReleased(evt);
            }
        });
        jPanel9.add(otherli, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 60, 140, -1));
        jPanel9.add(NonCurrTot, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 90, 120, -1));

        jPanel8.add(jPanel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 210, 460, 120));

        jPanel10.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel10.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel22.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel22.setText("CURRENT LIABILITIES");
        jPanel10.add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, -1));

        jLabel27.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel27.setText("Short Tearm Loans");
        jPanel10.add(jLabel27, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 40, -1, -1));

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel11.setText("Other Current liabilities");
        jPanel10.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 70, -1, -1));

        jLabel25.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel25.setText("Total");
        jPanel10.add(jLabel25, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 100, -1, -1));
        jPanel10.add(shortloan, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 40, 140, -1));
        jPanel10.add(othercurrloan, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 70, 140, -1));
        jPanel10.add(currli, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 100, 110, -1));

        jPanel8.add(jPanel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 340, 460, 130));

        jLabel26.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel26.setText("TOTAL LIABILITIES ");
        jPanel8.add(jLabel26, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 500, -1, -1));
        jPanel8.add(jTextField21, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 500, 140, -1));

        jPanel2.add(jPanel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 10, 500, 530));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 0, 980, 550));

        jButton1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton1.setText("Genarate Report");
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(1160, 460, -1, -1));

        jButton2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton2.setText("Reset All");
        jPanel1.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(1160, 490, -1, -1));

        jButton3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton3.setText("Demo");
        jPanel1.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(1160, 520, -1, -1));

        jTabbedPane1.addTab("Balance Sheet", jPanel1);

        getContentPane().add(jTabbedPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1350, 590));

        getAccessibleContext().setAccessibleName("");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cuAss_totActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cuAss_totActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cuAss_totActionPerformed

    private void investKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_investKeyReleased
        CalcfixTotal();
    }//GEN-LAST:event_investKeyReleased

    private void fundKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_fundKeyReleased
        // TODO add your handling code here:
        CalcLiaCap();
    }//GEN-LAST:event_fundKeyReleased

    private void CapitalKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_CapitalKeyReleased
      CalcLiaCap();
    }//GEN-LAST:event_CapitalKeyReleased

    private void ReseAndSupKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_ReseAndSupKeyReleased
        // TODO add your handling code here:
        CalcLiaCap();
    }//GEN-LAST:event_ReseAndSupKeyReleased

    private void longloanKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_longloanKeyReleased
        // TODO add your handling code here:
        CalcNonLiaCap();
    }//GEN-LAST:event_longloanKeyReleased

    private void otherliKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_otherliKeyReleased
        // TODO add your handling code here:
        CalcNonLiaCap();
    }//GEN-LAST:event_otherliKeyReleased

  
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField Bank;
    private javax.swing.JTextField Capital;
    private javax.swing.JTextField F_tot;
    private javax.swing.JTextField NonCurrTot;
    private javax.swing.JTextField ReseAndSup;
    private javax.swing.JTextField cashtot;
    private javax.swing.JTextField cuAss_tot;
    private javax.swing.JTextField currli;
    private javax.swing.JTextField deb;
    private javax.swing.JTextField fixassets;
    private javax.swing.JTextField fund;
    private javax.swing.JTextField invest;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel37;
    private javax.swing.JLabel jLabel38;
    private javax.swing.JLabel jLabel39;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTextField jTextField10;
    private javax.swing.JTextField jTextField14;
    private javax.swing.JTextField jTextField21;
    private javax.swing.JTextField liandcaptot;
    private javax.swing.JTextField longloan;
    private javax.swing.JTextField othercurrloan;
    private javax.swing.JTextField otherli;
    private javax.swing.JTextField shortloan;
    private javax.swing.JTextField stocktot;
    // End of variables declaration//GEN-END:variables

   

    
   
  

  

   
}
