
package Finance;


import MainSystem.AutoDB_Connect;
import static MainSystem.AutoDB_Connect.DB_connection;
import static MainSystem.MainWindow.autoSqlQuery;
import static MainSystem.MainWindow.validation;
import com.github.lgooddatepicker.components.DatePickerSettings;
import com.sun.glass.events.KeyEvent;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JOptionPane;
import net.proteanit.sql.DbUtils;


/**
 *
 * @author Dinushka
 */
public class LOANDETAILS extends javax.swing.JInternalFrame {



    /**
     * Creates new form SalesDesignInquiry
     */
    public LOANDETAILS() {
        initComponents();
        
         TableLoad();
         TextBoxClear();
         loantotal();

         
         
        datePicker1.setDateToToday();
    }
    
    
     public void loantotal()
    {
          try {
             PreparedStatement statement  =DB_connection.prepareStatement("SELECT SUM(Payment) FROM garmentsystem.F_LOANDETAILS;");
             ResultSet  results = statement.executeQuery();
                results.next();
                String sum = results.getString(1);
                System.out.println(sum);
                loantot.setText(sum);
            }
            
            catch (SQLException ex) 
                
             {
                System.out.println(ex.getMessage());
            }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        jTextField3 = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jTextField4 = new javax.swing.JTextField();
        amt1 = new javax.swing.JTextField();
        Mrate = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        payamt = new javax.swing.JTextField();
        AddjButton1 = new javax.swing.JButton();
        EditjButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jComboBox1 = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        DatePickerSettings dateSettings1 = new DatePickerSettings();
        dateSettings1.setFormatForDatesCommonEra("yyyy-MM-dd");
        dateSettings1.setFormatForDatesBeforeCommonEra("uuuu-MM-dd");
        datePicker1 = new com.github.lgooddatepicker.components.DatePicker(dateSettings1);
        jButton1 = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel4 = new javax.swing.JLabel();
        loantot = new javax.swing.JTextField();

        setResizable(true);
        setTitle("Loan Details");
        setMaximumSize(new java.awt.Dimension(1365, 620));
        setMinimumSize(new java.awt.Dimension(1365, 620));
        setPreferredSize(new java.awt.Dimension(1365, 620));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTabbedPane1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel9.setText("BANK LOAN DETAILS");
        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jPanel3.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        jLabel10.setText("Bank Name");
        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jPanel3.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 30, -1, -1));

        jLabel11.setText("Branch Name");
        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jPanel3.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 70, -1, -1));

        jLabel12.setText("Account No");
        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jPanel3.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 110, -1, -1));

        jLabel13.setText("Loan Amount");
        jLabel13.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jPanel3.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 220, -1, -1));

        jLabel16.setText("Month Interrest");
        jLabel16.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jPanel3.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 260, -1, -1));

        jTextField2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextField2KeyTyped(evt);
            }
        });
        jPanel3.add(jTextField2, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 50, 150, 30));

        jTextField3.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextField3KeyTyped(evt);
            }
        });
        jPanel3.add(jTextField3, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 90, 150, 30));

        jLabel1.setText("Loan period");
        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jPanel3.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 180, -1, -1));

        jTextField4.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextField4KeyTyped(evt);
            }
        });
        jPanel3.add(jTextField4, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 170, 150, 30));

        amt1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                amt1KeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                amt1KeyTyped(evt);
            }
        });
        jPanel3.add(amt1, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 210, 150, 30));

        Mrate.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                MrateKeyReleased(evt);
            }
        });
        jPanel3.add(Mrate, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 250, 150, 30));

        jLabel2.setText("Payment for Month");
        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jPanel3.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 300, -1, -1));
        jPanel3.add(payamt, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 290, 150, 30));

        AddjButton1.setText("ADD");
        AddjButton1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        AddjButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddjButton1ActionPerformed(evt);
            }
        });
        jPanel3.add(AddjButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 340, -1, -1));

        EditjButton2.setText("EDIT");
        EditjButton2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        EditjButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EditjButton2ActionPerformed(evt);
            }
        });
        jPanel3.add(EditjButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 340, -1, -1));

        jButton3.setText("SEARCH");
        jButton3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jPanel3.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 340, -1, -1));

        jButton4.setText("DELETE");
        jButton4.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        jPanel3.add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 340, -1, -1));

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select Bank", "BOC", "Peoples Bank", "HNB ", "UNION" }));
        jComboBox1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jPanel3.add(jComboBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 20, 150, -1));

        jLabel3.setText("Date");
        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jPanel3.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 140, -1, -1));
        jPanel3.add(datePicker1, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 130, 150, 30));

        jButton1.setText("Demo");
        jButton1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel3.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 340, -1, -1));

        jPanel2.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 0, 480, 380));

        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4", "Title 5", "Title 6", "Title 7"
            }
        ));
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        jPanel4.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, 770, 150));

        jLabel4.setText("Total");
        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jPanel4.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 190, 40, -1));
        jPanel4.add(loantot, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 180, 140, 30));

        jPanel2.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 10, 800, 220));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        jTabbedPane1.addTab("Loan Details", jPanel1);

        getContentPane().add(jTabbedPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1350, 590));

        getAccessibleContext().setAccessibleName("");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void AddjButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddjButton1ActionPerformed
        // TODO add your handling code here:
        AddLoan();
        TableLoad();
    }//GEN-LAST:event_AddjButton1ActionPerformed

    private void amt1KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_amt1KeyReleased
   
    }//GEN-LAST:event_amt1KeyReleased

    private void EditjButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EditjButton2ActionPerformed
        // TODO add your handling code here:
        EditLoan();
        TableLoad();
    }//GEN-LAST:event_EditjButton2ActionPerformed

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        // TODO add your handling code here:
           int row =jTable1.getSelectedRow(); 
        String b_name = jTable1.getValueAt(row,0).toString();
        String br_name = jTable1.getValueAt(row,1).toString();
        String acc_no = jTable1.getValueAt(row,2).toString();
        String date = jTable1.getValueAt(row,3).toString();
        String period = jTable1.getValueAt(row,4).toString();
        String amt = jTable1.getValueAt(row,5).toString();
        String inter = jTable1.getValueAt(row,6).toString();
        String payment = jTable1.getValueAt(row,7).toString();
        
         jComboBox1.setSelectedItem(b_name);
        jTextField2.setText(br_name);
        jTextField3.setText(acc_no);
        datePicker1.setText(date);
        jTextField4.setText(period);
        amt1.setText(amt);
        Mrate.setText(inter);
        payamt.setText(payment);
    }//GEN-LAST:event_jTable1MouseClicked

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
         
    }//GEN-LAST:event_jButton4ActionPerformed

    private void MrateKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_MrateKeyReleased

        float amount = Float.parseFloat(amt1.getText());
        
        float rate = Float.parseFloat(Mrate.getText());
        
        float depreciation = amount*(rate/100);
        
        
        //float mopay = amount-depreciation;
        
        payamt.setText(Double.toString(depreciation));
        
    }//GEN-LAST:event_MrateKeyReleased

    private void jTextField4KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField4KeyTyped
         char c=evt.getKeyChar();
      {
          if(!(Character.isDigit(c) || (c==KeyEvent.VK_BACKSPACE) ))
          {
              evt.consume();
              JOptionPane.showMessageDialog(this,"You can't enter Characters");
          }
      }
    }//GEN-LAST:event_jTextField4KeyTyped

    private void amt1KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_amt1KeyTyped
         char c=evt.getKeyChar();
      {
          if(!(Character.isDigit(c) || (c==KeyEvent.VK_BACKSPACE) ))
          {
              evt.consume();
              JOptionPane.showMessageDialog(this,"You can't enter Characters");
          }
      }
    }//GEN-LAST:event_amt1KeyTyped

    private void jTextField2KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField2KeyTyped
         char c=evt.getKeyChar();
      {
          if(!(Character.isLetter(c) || (c==KeyEvent.VK_BACKSPACE) ))
          {
              evt.consume();
              JOptionPane.showMessageDialog(this,"You can't enter Numbers");
          }
      }
    }//GEN-LAST:event_jTextField2KeyTyped

    private void jTextField3KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField3KeyTyped
        // TODO add your handling code here:
        
        {                              
        char c=evt.getKeyChar();
      {
          if(!(Character.isDigit(c) || (c==KeyEvent.VK_BACKSPACE) ))
          {
              evt.consume();
              JOptionPane.showMessageDialog(this,"You can't enter Characters");
          }
      }
    }                             

    }//GEN-LAST:event_jTextField3KeyTyped

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        jComboBox1.setSelectedItem("BOC");
        jTextField2.setText("kaluthara");
        jTextField3.setText("7895836987");
        jTextField4.setText("4");
        amt1.setText("780000");
        Mrate.setText("5");
        
        
    }//GEN-LAST:event_jButton1ActionPerformed
   
      private void TableLoad()
  {
      AutoDB_Connect.DB_ResultSet = autoSqlQuery.executeQuery("SELECT `F_LOANDETAILS`.`BankName`,\n" +
"    `F_LOANDETAILS`.`BranchName`,\n" +
"    `F_LOANDETAILS`.`AccNo`,\n" +
"    `F_LOANDETAILS`.`Date`,\n" +
"    `F_LOANDETAILS`.`Period`,\n" +
"    `F_LOANDETAILS`.`Ammount`,\n" +
"    `F_LOANDETAILS`.`Month Interest`,\n" +
"    `F_LOANDETAILS`.`Payment`\n" +
"FROM `garmentsystem`.`F_LOANDETAILS`;");
       jTable1.setModel(DbUtils.resultSetToTableModel(AutoDB_Connect.DB_ResultSet));
  }
    public void AddLoan()
    {
        
           String b_name = jComboBox1.getSelectedItem().toString();
        String br_name = jTextField2.getText();
        String acc_no = jTextField3.getText();
        String date = datePicker1.getText();
        String period = jTextField4.getText();
        String amt = amt1.getText();
        String inter = Mrate.getText();
        String payment = payamt.getText();
        
        boolean x = autoSqlQuery.execute("INSERT INTO `garmentsystem`.`F_LOANDETAILS`\n" +
"(`BankName`,\n" +
"`BranchName`,\n" +
"`AccNo`,\n" +
"`Date`,\n" +
"`Period`,\n" +
"`Ammount`,\n" +
"`Month Interest`,\n" +
"`Payment`)\n" +
"VALUES\n" +
"('"+b_name+"',\n" +
"'"+br_name+"',\n" +
"'"+acc_no+"',\n" +
"'"+date+"',\n" +
"'"+period+"',\n" +
""+amt+",\n" +
"'"+inter+"',\n" +
"'"+payment+"');");
        
        
          try
        {
            if(x==true)
            {
                TableLoad();
                TextBoxClear();
                JOptionPane.showMessageDialog(null,"Successfully Added");
            }
        }
        catch (Exception ex)
        {
            System.out.println(ex);
        }    
    
    }
private void TextBoxClear()
{
        jComboBox1.setSelectedIndex(0);
        jTextField2.setText("");
        jTextField3.setText("");
        datePicker1.setDateToToday();
        jTextField4.setText("");
        amt1.setText("");
        Mrate.setText("");
        payamt.setText("");
}
public void EditLoan()
{
     if(validation.ValidationCheck(jTextField2, true, 0, '@')
        &&validation.ValidationCheck(jTextField3, true,0,'@')
        &&validation.ValidationCheck(jTextField4, true,0,'1')
        &&validation.ValidationCheck(amt1, true,0,'1')
        &&validation.ValidationCheck(Mrate, true,0,'1')
        &&validation.ValidationCheck(payamt, true,0,'1'))
     {
     String b_name = jComboBox1.getSelectedItem().toString();
        String br_name = jTextField2.getText();
        String acc_no = jTextField3.getText();
        String date = datePicker1.getText();
        String period = jTextField4.getText();
        String amt = amt1.getText();
        String inter = Mrate.getText();
        String payment = payamt.getText();
        
         boolean x = autoSqlQuery.execute("UPDATE `garmentsystem`.`F_LOANDETAILS`\n" +
"SET\n" +
"`BankName` = '"+b_name+"',\n" +
"`BranchName` = '"+br_name+"',\n" +
"`AccNo` = '"+acc_no+"',\n" +
"`Date` = '"+date+"',\n" +
"`Period` = '"+period+"',\n" +
"`Ammount` = "+amt+",\n" +
"`Month Interest` = '"+inter+"',\n" +
"`Payment` = '"+payment+"'\n" +
"WHERE `AccNo` = '"+acc_no+"',\n;");
          try
        {
            if (x==true)
            {
               TextBoxClear();
               TableLoad();
               JOptionPane.showMessageDialog(null,"Successfully Updated");
            }
        }
        catch (Exception ex){
            System.out.println(ex);
        }
}
}
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AddjButton1;
    private javax.swing.JButton EditjButton2;
    private javax.swing.JTextField Mrate;
    private javax.swing.JTextField amt1;
    private com.github.lgooddatepicker.components.DatePicker datePicker1;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField loantot;
    private javax.swing.JTextField payamt;
    // End of variables declaration//GEN-END:variables

  
}
