
package Procurements;

import MainSystem.AutoIdGenerator;
import MainSystem.AutoDB_Connect;
import MainSystem.MainWindow;
import net.proteanit.sql.DbUtils;
import static MainSystem.MainWindow.autoSqlQuery;
import com.github.lgooddatepicker.components.DatePickerSettings;


/**
 *
 * @author Dinushka
 */
public class ReturnGoods extends javax.swing.JInternalFrame {

    public ReturnGoods() {
        initComponents();
        TableLoad();
        MaterialLoad();
        AccessoryLoad();
        MachinePartsLoad();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();
        jPanel1 = new javax.swing.JPanel();
        cancelOrder = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        odno = new javax.swing.JTextField();
        des = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        qty = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        unit = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        tot = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        adv = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jRadioButton1 = new javax.swing.JRadioButton();
        jRadioButton2 = new javax.swing.JRadioButton();
        jPanel4 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        DatePickerSettings dateSettings01 = new DatePickerSettings();
        dateSettings01.setFormatForDatesCommonEra("yyyy-MM-dd");
        dateSettings01.setFormatForDatesBeforeCommonEra("uuuu-MM-dd");
        datePicker1 = new com.github.lgooddatepicker.components.DatePicker(dateSettings01);
        spp = new javax.swing.JComboBox<>();
        jButton6 = new javax.swing.JButton();
        returnInventory = new javax.swing.JPanel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel2 = new javax.swing.JPanel();
        jPanel7 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jTextField3 = new javax.swing.JTextField();
        jTextField4 = new javax.swing.JTextField();
        jTextField5 = new javax.swing.JTextField();
        jTextField6 = new javax.swing.JTextField();
        DatePickerSettings dateSettings2 = new DatePickerSettings();
        dateSettings2.setFormatForDatesCommonEra("yyyy-MM-dd");
        dateSettings2.setFormatForDatesBeforeCommonEra("uuuu-MM-dd");
        datePicker2 = new com.github.lgooddatepicker.components.DatePicker(dateSettings2);
        DeleteButton = new javax.swing.JButton();
        jPanel8 = new javax.swing.JPanel();
        jScrollPane4 = new javax.swing.JScrollPane();
        jTable4 = new javax.swing.JTable();
        jPanel5 = new javax.swing.JPanel();
        jPanel9 = new javax.swing.JPanel();
        DeleteButton1 = new javax.swing.JButton();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel31 = new javax.swing.JLabel();
        DatePickerSettings dateSettings3 = new DatePickerSettings();
        dateSettings3.setFormatForDatesCommonEra("yyyy-MM-dd");
        dateSettings3.setFormatForDatesBeforeCommonEra("uuuu-MM-dd");
        datePicker3 = new com.github.lgooddatepicker.components.DatePicker(dateSettings3);
        typefield1 = new javax.swing.JTextField();
        valuefield1 = new javax.swing.JTextField();
        quantityfield1 = new javax.swing.JTextField();
        costfield1 = new javax.swing.JTextField();
        namefield1 = new javax.swing.JTextField();
        idfield1 = new javax.swing.JTextField();
        jLabel24 = new javax.swing.JLabel();
        reorder1 = new javax.swing.JTextField();
        jPanel10 = new javax.swing.JPanel();
        jScrollPane5 = new javax.swing.JScrollPane();
        jTable5 = new javax.swing.JTable();
        jPanel6 = new javax.swing.JPanel();
        jPanel11 = new javax.swing.JPanel();
        DeleteButton2 = new javax.swing.JButton();
        idfield2 = new javax.swing.JTextField();
        jLabel25 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        namefield2 = new javax.swing.JTextField();
        jLabel27 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        valuefield2 = new javax.swing.JTextField();
        qtyfield1 = new javax.swing.JTextField();
        jLabel29 = new javax.swing.JLabel();
        jLabel30 = new javax.swing.JLabel();
        DatePickerSettings dateSettings4 = new DatePickerSettings();
        dateSettings4.setFormatForDatesCommonEra("yyyy-MM-dd");
        dateSettings4.setFormatForDatesBeforeCommonEra("uuuu-MM-dd");
        datePicker4 = new com.github.lgooddatepicker.components.DatePicker(dateSettings4);
        machinenumber = new javax.swing.JTextField();
        jPanel12 = new javax.swing.JPanel();
        jScrollPane6 = new javax.swing.JScrollPane();
        jTable6 = new javax.swing.JTable();

        setResizable(true);
        setTitle("Return Goods");
        setMaximumSize(new java.awt.Dimension(1365, 620));
        setMinimumSize(new java.awt.Dimension(1365, 620));
        setPreferredSize(new java.awt.Dimension(1365, 620));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel1.setText("Select return Good Type :");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, -1, -1));

        jComboBox1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Cancel Order and Return Goods", "Return Goods from Inventory" }));
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });
        getContentPane().add(jComboBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 20, 200, -1));

        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel1.setLayout(new java.awt.CardLayout());

        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setText("Order No");
        jPanel3.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 30, -1, -1));

        jLabel3.setText("Purchase Description");
        jPanel3.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 80, -1, -1));
        jPanel3.add(odno, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 30, 210, -1));
        jPanel3.add(des, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 80, 210, -1));

        jLabel6.setText("Quantity");
        jPanel3.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 120, -1, -1));
        jPanel3.add(qty, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 120, 210, -1));

        jLabel7.setText("Unit price");
        jPanel3.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 160, -1, -1));

        unit.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                unitKeyReleased(evt);
            }
        });
        jPanel3.add(unit, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 160, 210, -1));

        jLabel8.setText("Supplier");
        jPanel3.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 310, -1, -1));

        jLabel11.setText("Total amount");
        jPanel3.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 200, -1, -1));

        tot.setEditable(false);
        tot.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                totKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                totKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                totKeyTyped(evt);
            }
        });
        jPanel3.add(tot, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 200, 210, -1));

        jLabel12.setText("Advance");
        jPanel3.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 230, -1, -1));
        jPanel3.add(adv, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 230, 210, -1));

        jLabel13.setText("Estimated delivery");
        jPanel3.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 360, -1, -1));

        jLabel14.setText("Payment method");
        jPanel3.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 270, -1, -1));

        buttonGroup1.add(jRadioButton1);
        jRadioButton1.setText("Credit");
        jPanel3.add(jRadioButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 270, -1, -1));

        buttonGroup1.add(jRadioButton2);
        jRadioButton2.setText("Cash");
        jPanel3.add(jRadioButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 270, -1, -1));

        jPanel4.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        jPanel4.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 800, 470));

        jPanel3.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 0, 830, 490));
        jPanel3.add(datePicker1, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 350, 210, -1));

        jPanel3.add(spp, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 310, 210, -1));

        jButton6.setText("Cancel Order and Return Goods");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        jPanel3.add(jButton6, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 430, -1, -1));

        cancelOrder.add(jPanel3);

        jPanel1.add(cancelOrder, "card2");

        returnInventory.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTabbedPane1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N

        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel7.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel4.setText("Material ID");
        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N

        jLabel5.setText("Material Name");
        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N

        jLabel9.setText("Material Cost Per Unit");
        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N

        jLabel10.setText("Quantity");
        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N

        jLabel15.setText("Material Value");
        jLabel15.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N

        jLabel16.setText("Re-Order Quantity");
        jLabel16.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N

        jLabel17.setText("Date");
        jLabel17.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N

        jTextField1.setEditable(false);
        jTextField1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        jTextField2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        jTextField3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        jTextField4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jTextField4.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTextField4KeyReleased(evt);
            }
        });

        jTextField5.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        jTextField6.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        datePicker1.setName(""); // NOI18N
        datePicker2.setEnabled(false);
        datePicker2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        DeleteButton.setText("Remove from Inventory");
        DeleteButton.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        DeleteButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DeleteButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGap(68, 68, 68)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(DeleteButton, javax.swing.GroupLayout.PREFERRED_SIZE, 319, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5)
                            .addComponent(jLabel9)
                            .addComponent(jLabel10)
                            .addComponent(jLabel15)
                            .addComponent(jLabel16)
                            .addComponent(jLabel17))
                        .addGap(88, 88, 88)
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jTextField6)
                            .addComponent(jTextField5)
                            .addComponent(jTextField4)
                            .addComponent(jTextField3)
                            .addComponent(jTextField2)
                            .addComponent(jTextField1)
                            .addComponent(datePicker2, javax.swing.GroupLayout.DEFAULT_SIZE, 182, Short.MAX_VALUE))))
                .addContainerGap(124, Short.MAX_VALUE))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(23, 23, 23)
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel5)
                            .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(22, 22, 22)
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel9)
                            .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(26, 26, 26)
                        .addComponent(jLabel10))
                    .addComponent(jTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(23, 23, 23)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel15)
                    .addComponent(jTextField5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(31, 31, 31)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addComponent(jLabel16)
                        .addGap(62, 62, 62))
                    .addComponent(jLabel17)
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addComponent(jTextField6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(33, 33, 33)
                        .addComponent(datePicker2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addComponent(DeleteButton)
                .addContainerGap(55, Short.MAX_VALUE))
        );

        jPanel2.add(jPanel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 600, 430));

        jPanel8.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel8.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTable4.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jTable4.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jTable4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable4MouseClicked(evt);
            }
        });
        jScrollPane4.setViewportView(jTable4);

        jPanel8.add(jScrollPane4, new org.netbeans.lib.awtextra.AbsoluteConstraints(16, 7, 650, 410));

        jPanel2.add(jPanel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 10, 680, 430));

        jTabbedPane1.addTab("Raw Materials", jPanel2);

        jPanel5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel9.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        jPanel9.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        DeleteButton1.setText("Remove from Inventory");
        DeleteButton1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        DeleteButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DeleteButton1ActionPerformed(evt);
            }
        });
        jPanel9.add(DeleteButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 376, 200, -1));

        jLabel18.setText("Accessory ID");
        jLabel18.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jPanel9.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(54, 24, 129, -1));

        jLabel19.setText("Accessory Name");
        jLabel19.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jPanel9.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(54, 62, 129, -1));

        jLabel20.setText("Cost Per Unit");
        jLabel20.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jPanel9.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(54, 107, 129, -1));

        jLabel23.setText("Quantity");
        jLabel23.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jPanel9.add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(54, 154, -1, -1));

        jLabel21.setText("Stock Value");
        jLabel21.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jPanel9.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(54, 203, 129, -1));

        jLabel22.setText("Accessory Type");
        jLabel22.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jPanel9.add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(54, 254, -1, -1));

        jLabel31.setText("Date");
        jLabel31.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jPanel9.add(jLabel31, new org.netbeans.lib.awtextra.AbsoluteConstraints(54, 328, -1, -1));

        datePicker3.setEnabled(false);
        datePicker3.setName(""); // NOI18N
        jPanel9.add(datePicker3, new org.netbeans.lib.awtextra.AbsoluteConstraints(271, 325, 229, -1));

        typefield1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jPanel9.add(typefield1, new org.netbeans.lib.awtextra.AbsoluteConstraints(271, 248, 229, -1));

        valuefield1.setEnabled(false);
        valuefield1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        valuefield1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                valuefield1KeyReleased(evt);
            }
        });
        jPanel9.add(valuefield1, new org.netbeans.lib.awtextra.AbsoluteConstraints(271, 197, 229, -1));

        quantityfield1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                quantityfield1ActionPerformed(evt);
            }
        });
        quantityfield1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                quantityfield1KeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                quantityfield1KeyTyped(evt);
            }
        });
        jPanel9.add(quantityfield1, new org.netbeans.lib.awtextra.AbsoluteConstraints(271, 151, 229, -1));
        jPanel9.add(costfield1, new org.netbeans.lib.awtextra.AbsoluteConstraints(271, 104, 229, -1));

        namefield1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                namefield1ActionPerformed(evt);
            }
        });
        jPanel9.add(namefield1, new org.netbeans.lib.awtextra.AbsoluteConstraints(271, 59, 229, -1));

        idfield1.setEditable(false);
        jPanel9.add(idfield1, new org.netbeans.lib.awtextra.AbsoluteConstraints(271, 21, 229, -1));

        jLabel24.setText("Re-Order Level");
        jLabel24.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jPanel9.add(jLabel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(54, 283, 97, -1));

        reorder1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jPanel9.add(reorder1, new org.netbeans.lib.awtextra.AbsoluteConstraints(271, 277, 229, -1));

        jPanel5.add(jPanel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 560, 430));

        jPanel10.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        jTable5.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jTable5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable5MouseClicked(evt);
            }
        });
        jScrollPane5.setViewportView(jTable5);

        javax.swing.GroupLayout jPanel10Layout = new javax.swing.GroupLayout(jPanel10);
        jPanel10.setLayout(jPanel10Layout);
        jPanel10Layout.setHorizontalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane5, javax.swing.GroupLayout.DEFAULT_SIZE, 646, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel10Layout.setVerticalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane5, javax.swing.GroupLayout.DEFAULT_SIZE, 403, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanel5.add(jPanel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 10, 670, 430));

        jTabbedPane1.addTab("Accessories", jPanel5);

        jPanel6.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel11.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        jPanel11.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        DeleteButton2.setText("Remove from Inventory");
        DeleteButton2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        DeleteButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DeleteButton2ActionPerformed(evt);
            }
        });
        jPanel11.add(DeleteButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(329, 370, 200, -1));

        idfield2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jPanel11.add(idfield2, new org.netbeans.lib.awtextra.AbsoluteConstraints(319, 23, 188, -1));

        jLabel25.setText("Machine Part ID");
        jLabel25.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jPanel11.add(jLabel25, new org.netbeans.lib.awtextra.AbsoluteConstraints(47, 29, -1, -1));

        jLabel26.setText("Machine Part Name");
        jLabel26.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jPanel11.add(jLabel26, new org.netbeans.lib.awtextra.AbsoluteConstraints(47, 75, 133, -1));

        namefield2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jPanel11.add(namefield2, new org.netbeans.lib.awtextra.AbsoluteConstraints(319, 69, 188, -1));

        jLabel27.setText("Machine Number");
        jLabel27.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jPanel11.add(jLabel27, new org.netbeans.lib.awtextra.AbsoluteConstraints(47, 123, 133, -1));

        jLabel28.setText("Part Value");
        jLabel28.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jPanel11.add(jLabel28, new org.netbeans.lib.awtextra.AbsoluteConstraints(47, 172, 96, -1));

        valuefield2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jPanel11.add(valuefield2, new org.netbeans.lib.awtextra.AbsoluteConstraints(319, 166, 188, -1));

        qtyfield1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jPanel11.add(qtyfield1, new org.netbeans.lib.awtextra.AbsoluteConstraints(319, 216, 188, -1));

        jLabel29.setText("Quantity");
        jLabel29.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jPanel11.add(jLabel29, new org.netbeans.lib.awtextra.AbsoluteConstraints(47, 222, 96, -1));

        jLabel30.setText("Purchased Date");
        jLabel30.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jPanel11.add(jLabel30, new org.netbeans.lib.awtextra.AbsoluteConstraints(46, 268, -1, -1));

        datePicker4.setEnabled(false);
        datePicker4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        datePicker4.setName(""); // NOI18N
        jPanel11.add(datePicker4, new org.netbeans.lib.awtextra.AbsoluteConstraints(319, 269, 188, -1));

        machinenumber.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jPanel11.add(machinenumber, new org.netbeans.lib.awtextra.AbsoluteConstraints(319, 117, 188, -1));

        jPanel6.add(jPanel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 600, 430));

        jPanel12.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        jTable6.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jTable6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable6MouseClicked(evt);
            }
        });
        jScrollPane6.setViewportView(jTable6);

        javax.swing.GroupLayout jPanel12Layout = new javax.swing.GroupLayout(jPanel12);
        jPanel12.setLayout(jPanel12Layout);
        jPanel12Layout.setHorizontalGroup(
            jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel12Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane6, javax.swing.GroupLayout.DEFAULT_SIZE, 626, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel12Layout.setVerticalGroup(
            jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel12Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane6, javax.swing.GroupLayout.DEFAULT_SIZE, 403, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanel6.add(jPanel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 10, 650, 430));

        jTabbedPane1.addTab("Machine Parts", jPanel6);

        returnInventory.add(jTabbedPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 1310, 480));

        jPanel1.add(returnInventory, "card3");

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 60, 1330, 510));

        getAccessibleContext().setAccessibleName("");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void unitKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_unitKeyReleased

        double qty1 = Double.parseDouble(qty.getText());
        double perunit = Double.parseDouble(unit.getText());

        double tot1 = perunit * qty1;

        tot.setText(Double.toString(tot1));

    }//GEN-LAST:event_unitKeyReleased

    private void totKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_totKeyPressed

    }//GEN-LAST:event_totKeyPressed

    private void totKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_totKeyReleased

    }//GEN-LAST:event_totKeyReleased

    private void totKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_totKeyTyped

    }//GEN-LAST:event_totKeyTyped

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked

        int row = jTable1.getSelectedRow();
        String id = jTable1.getValueAt(row,0).toString();
        String description = jTable1.getValueAt(row,1).toString();
        String quantity = jTable1.getValueAt(row,3).toString();
        String unitprice = jTable1.getValueAt(row,4).toString();
        String total = jTable1.getValueAt(row,5).toString();
        String advance = jTable1.getValueAt(row,6).toString();
        String paymenttype = jTable1.getValueAt(row,7).toString();
        String spplier = jTable1.getValueAt(row,8).toString();
        String date = jTable1.getValueAt(row,9).toString();

        odno.setText(id);
        des.setText(description);
        qty.setText(quantity);
        unit.setText(unitprice);
        tot.setText(total);
        adv.setText(advance);

        jRadioButton1.setActionCommand("Credit");
        jRadioButton2.setActionCommand("Cash");

        if("Credit".equals(paymenttype))
        {
            jRadioButton1.setSelected(true);
        }
        else if("Cash".equals(paymenttype))
        {
            jRadioButton2.setSelected(true);
        }

        spp.setSelectedItem(spplier);
        datePicker1.setDateToToday();
    }//GEN-LAST:event_jTable1MouseClicked

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        DeleteOrder();
    }//GEN-LAST:event_jButton6ActionPerformed

    private void AccessoryLoad()
    {

            AutoDB_Connect.DB_ResultSet = autoSqlQuery.executeQuery("SELECT * FROM garmentsystem.Accessory_Table");
            jTable5.setModel(DbUtils.resultSetToTableModel(AutoDB_Connect.DB_ResultSet));

    }
    
    private void MaterialLoad()
    {

            AutoDB_Connect.DB_ResultSet = autoSqlQuery.executeQuery("SELECT * FROM garmentsystem.Raw_Materials");
            jTable4.setModel(DbUtils.resultSetToTableModel(AutoDB_Connect.DB_ResultSet));

    }
    
    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed

        if(jComboBox1.getSelectedItem().equals("Cancel Order and Return Goods"))
        {
            cancelOrder.setVisible(true);
            returnInventory.setVisible(false);
        }
        else if(jComboBox1.getSelectedItem().equals("Return Goods from Inventory"))
        {
            returnInventory.setVisible(true);
            cancelOrder.setVisible(false);
        }
    }//GEN-LAST:event_jComboBox1ActionPerformed

    private void jTextField4KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField4KeyReleased
        // TODO add your handling code here:
        double perunit = Double.parseDouble(jTextField3.getText());
        double qty = Double.parseDouble(jTextField4.getText());

        double val = perunit * qty;

        jTextField5.setText(Double.toString(val));
    }//GEN-LAST:event_jTextField4KeyReleased

    private void DeleteButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DeleteButtonActionPerformed
        // TODO add your handling code here:
        String id = jTextField1.getText();

        boolean x = autoSqlQuery.execute("DELETE FROM `garmentsystem`.`Raw_Materials`\n" +
            "WHERE Material_id = '"+id+"';");

        try
        {
            if (x==true)
            {
                TextBoxClear2();
                MaterialLoad();
            }
        }
        catch (Exception ex){
            System.out.println(ex);
        }

        
    }//GEN-LAST:event_DeleteButtonActionPerformed

    private void jTable4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable4MouseClicked
        // TODO add your handling code here:
        int row =jTable4.getSelectedRow();
        String id = jTable4.getValueAt(row,0).toString();
        String name = jTable4.getValueAt(row,1).toString();
        String cost = jTable4.getValueAt(row,2).toString();
        String qty = jTable4.getValueAt(row,3).toString();
        String value = jTable4.getValueAt(row,4).toString();
        String reorder = jTable4.getValueAt(row,5).toString();
        String date = jTable4.getValueAt(row,6).toString();

        jTextField1.setText(id);
        jTextField2.setText(name);
        jTextField3.setText(cost);
        jTextField4.setText(qty);
        jTextField5.setText(value);
        jTextField6.setText(reorder);
        datePicker2.setText(date);

    }//GEN-LAST:event_jTable4MouseClicked

    private void DeleteButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DeleteButton1ActionPerformed

        DeleteAccessory();
        clear();
    }//GEN-LAST:event_DeleteButton1ActionPerformed

    private void clear()
    {
        idfield1.setText("");
        namefield1.setText("");
        costfield1.setText("");
        quantityfield1.setText("");
        valuefield1.setText("");
        typefield1.setText("");
        reorder1.setText("");
        datePicker3.setText("");
        
    }
    
    private void DeleteAccessory()
    {
        String id = idfield1.getText();
        
        boolean x = autoSqlQuery.execute("DELETE FROM `garmentsystem`.`Accessory_Table`\n" +
"WHERE accessory_id = '"+id+"';");
        
        try
        {
            if (x==true)
            {
                clear();
                AccessoryLoad();
            }
        }
        catch (Exception ex){
            System.out.println(ex);
        }
    }
    
    private void valuefield1KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_valuefield1KeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_valuefield1KeyReleased

    private void quantityfield1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_quantityfield1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_quantityfield1ActionPerformed

    private void quantityfield1KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_quantityfield1KeyReleased

        double qty = Double.parseDouble(quantityfield1.getText());
        double perunit = Double.parseDouble(costfield1.getText());

        double val = perunit * qty;

        valuefield1.setText(Double.toString(val));
    }//GEN-LAST:event_quantityfield1KeyReleased

    private void quantityfield1KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_quantityfield1KeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_quantityfield1KeyTyped

    private void namefield1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_namefield1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_namefield1ActionPerformed

    private void jTable5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable5MouseClicked
        // TODO add your handling code here:
        int row =jTable5.getSelectedRow();
        String id = jTable5.getValueAt(row,0).toString();
        String name = jTable5.getValueAt(row,1).toString();
        String cost = jTable5.getValueAt(row,2).toString();
        String qty = jTable5.getValueAt(row,3).toString();
        String value = jTable5.getValueAt(row,4).toString();
        String type = jTable5.getValueAt(row,5).toString();
        String roder = jTable5.getValueAt(row,6).toString();
        String date = jTable5.getValueAt(row,7).toString();

        idfield1.setText(id);
        namefield1.setText(name);
        costfield1.setText(cost);
        quantityfield1.setText(qty);
        valuefield1.setText(value);
        typefield1.setText(type);
        reorder1.setText(roder);
        datePicker3.setText(date);

    }//GEN-LAST:event_jTable5MouseClicked

    private void DeleteButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DeleteButton2ActionPerformed
        // TODO add your handling code here:
        String id = idfield2.getText();

        boolean x = autoSqlQuery.execute("DELETE FROM `garmentsystem`.`MachineParts_Table`\n" +
            "WHERE part_id = '"+id+"';");

        try
        {
            if (x==true)
            {
                MachinePartsLoad();
                MachinePartsClear();
            }
        }
        catch (Exception ex){
            System.out.println(ex);
        }

        //        DB_Connect.DB_ResultSet = autoSqlQuery.executeQuery("DELETE FROM `garmentsystem`.`Raw_Materials`\n" +
            //"WHERE Material_id = '"+id+"';");

    }//GEN-LAST:event_DeleteButton2ActionPerformed

    private void MachinePartsClear()
    {
        idfield2.setText("");
        namefield2.setText("");
        machinenumber.setText("");
        valuefield2.setText("");
        qtyfield1.setText("");
        datePicker4.setText("");
    }
    private void jTable6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable6MouseClicked

        
        int row =jTable6.getSelectedRow();
        String id = jTable6.getValueAt(row,0).toString();
        String name = jTable6.getValueAt(row,1).toString();
        String macnum = jTable6.getValueAt(row,2).toString();
        String value = jTable6.getValueAt(row,3).toString();
        String qty = jTable6.getValueAt(row,4).toString();
        String date = jTable6.getValueAt(row,5).toString();

        idfield2.setText(id);
        namefield2.setText(name);
        machinenumber.setText(macnum);
        valuefield2.setText(value);
        qtyfield1.setText(qty);
        datePicker4.setText(date);

    }//GEN-LAST:event_jTable6MouseClicked
    
    private void MachinePartsLoad()
    {
            AutoDB_Connect.DB_ResultSet = autoSqlQuery.executeQuery("SELECT * FROM garmentsystem.MachineParts_Table");
            jTable6.setModel(DbUtils.resultSetToTableModel(AutoDB_Connect.DB_ResultSet));

    
    }
    
    private void TextBoxClear2()
    {
        jTextField1.setText("");
        jTextField2.setText("");
        jTextField3.setText("");
        jTextField4.setText("");
        jTextField5.setText("");
        jTextField6.setText("");
        datePicker1.setText("");
    }
    
    private void DeleteOrder()
    {
        
        
            String id = odno.getText();
        
        boolean x = autoSqlQuery.execute("DELETE FROM `garmentsystem`.`Purchasing`\n" +
"WHERE Order_ID='"+id+"';");
        
        try
        {
            if(x==true)
            {
                TableLoad();
                TextBoxClear();
            }
        }
        catch(Exception ex)
        {
            System.out.println(ex);
        }
        
        
    }
    
    private void TableLoad()
    {
        AutoDB_Connect.DB_ResultSet = autoSqlQuery.executeQuery("SELECT * from `garmentsystem`.`Purchasing`");
        jTable1.setModel(DbUtils.resultSetToTableModel(AutoDB_Connect.DB_ResultSet));
    }
   
    private void TextBoxClear()
    {
        odno.setText("");
        des.setText("");
        qty.setText("");
        unit.setText("");
        tot.setText("");
        adv.setText("");
        
                
        spp.setSelectedIndex(0);
        datePicker1.setDateToToday();
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton DeleteButton;
    private javax.swing.JButton DeleteButton1;
    private javax.swing.JButton DeleteButton2;
    private javax.swing.JTextField adv;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JPanel cancelOrder;
    private javax.swing.JTextField costfield1;
    private com.github.lgooddatepicker.components.DatePicker datePicker1;
    private com.github.lgooddatepicker.components.DatePicker datePicker2;
    private com.github.lgooddatepicker.components.DatePicker datePicker3;
    private com.github.lgooddatepicker.components.DatePicker datePicker4;
    private javax.swing.JTextField des;
    private javax.swing.JTextField idfield1;
    private javax.swing.JTextField idfield2;
    private javax.swing.JButton jButton6;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel12;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JRadioButton jRadioButton2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable jTable2;
    private javax.swing.JTable jTable3;
    private javax.swing.JTable jTable4;
    private javax.swing.JTable jTable5;
    private javax.swing.JTable jTable6;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTextField jTextField6;
    private javax.swing.JTextField machinenumber;
    private javax.swing.JTextField namefield1;
    private javax.swing.JTextField namefield2;
    private javax.swing.JTextField odno;
    private javax.swing.JTextField qty;
    private javax.swing.JTextField qtyfield1;
    private javax.swing.JTextField quantityfield1;
    private javax.swing.JTextField reorder1;
    private javax.swing.JPanel returnInventory;
    private javax.swing.JComboBox<String> spp;
    private javax.swing.JTextField tot;
    private javax.swing.JTextField typefield1;
    private javax.swing.JTextField unit;
    private javax.swing.JTextField valuefield1;
    private javax.swing.JTextField valuefield2;
    // End of variables declaration//GEN-END:variables
}
