
package Sales;

import MainSystem.AutoDB_Connect;
import static MainSystem.MainWindow.autoSqlQuery;
import com.github.lgooddatepicker.components.DatePickerSettings;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import net.proteanit.sql.DbUtils;


/**
 *
 * @author Dinushka
 */
public class SalesInvoice extends javax.swing.JInternalFrame {

SalesInvoiceModel salesinvoicemodel;
    /**
     * Creates new form SalesDesignInquiry
     */
String CustomerId;
String CustomerName;
String ProductID;
String ProductName;
String Price;
String Quantity;
String SalesInquriyId;
DefaultTableModel ProductModel;
 DefaultTableModel sedmodel1;
 DefaultTableModel sedmodel2;
 DefaultTableModel ProductModel1;
int RowCountjTable1;

String ProductID1;
String ProductName1;
String Price1;
String Quantity1;


    public SalesInvoice() {
        initComponents();
        salesinvoicemodel= new SalesInvoiceModel(); 
        jPanelcustomerSearch1.setVisible(false);
        jPanelSalesInquirySearch.setVisible(false);
        jPanelproductSearch.setVisible(false);
        jTextFieldSalesInvoiceId.setText(salesinvoicemodel.generate_sin());
        datePickerSalesInvoice.setDateToToday();
        ProductModel = (DefaultTableModel) jTableSalesInvoice.getModel();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableSalesInvoice = new javax.swing.JTable();
        jPanel6 = new javax.swing.JPanel();
        jButton6 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jTextFieldCustomerID = new javax.swing.JTextField();
        jTextFieldCustomerName = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jTextFieldSalesInvoiceId = new javax.swing.JTextField();
        DatePickerSettings dateSettings = new DatePickerSettings();
        dateSettings.setFormatForDatesCommonEra("yyyy/MM/dd");
        dateSettings.setFormatForDatesBeforeCommonEra("uuuu/MM/dd");
        datePickerSalesInvoice = new com.github.lgooddatepicker.components.DatePicker(dateSettings);
        jButton11 = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jTextFieldSalesInquiryId = new javax.swing.JTextField();
        jButton12 = new javax.swing.JButton();
        jButtonADD = new javax.swing.JButton();
        jButton13 = new javax.swing.JButton();
        jButton18 = new javax.swing.JButton();
        jTextFieldTotal = new javax.swing.JTextField();
        jLabel26 = new javax.swing.JLabel();
        jTextFieldGrandTotal = new javax.swing.JTextField();
        jLabel23 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        jComboBoxDiscountRate = new javax.swing.JComboBox<>();
        jButton36 = new javax.swing.JButton();
        jPanelcustomerSearch1 = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTableSCustomer = new javax.swing.JTable();
        jButton14 = new javax.swing.JButton();
        jTextField10 = new javax.swing.JTextField();
        jTextField11 = new javax.swing.JTextField();
        jTextFieldSDICustomerId = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jButton15 = new javax.swing.JButton();
        jButton16 = new javax.swing.JButton();
        jButton17 = new javax.swing.JButton();
        jButton20 = new javax.swing.JButton();
        jPanelSalesInquirySearch = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTablesSalesInquiry = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        jTextFieldSearchCustomerName = new javax.swing.JTextField();
        jTextFieldSearchCustomerPhone = new javax.swing.JTextField();
        jTextFieldSearchCustomerId = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jButton8 = new javax.swing.JButton();
        jButton9 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton10 = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jButton25 = new javax.swing.JButton();
        jButton35 = new javax.swing.JButton();
        jPanelproductSearch = new javax.swing.JPanel();
        jScrollPane6 = new javax.swing.JScrollPane();
        jTablesProduct = new javax.swing.JTable();
        jButton27 = new javax.swing.JButton();
        jTextField12 = new javax.swing.JTextField();
        jTextField13 = new javax.swing.JTextField();
        jTextFieldSDIpprId1 = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jButton28 = new javax.swing.JButton();
        jButton29 = new javax.swing.JButton();
        jButton30 = new javax.swing.JButton();
        jButton34 = new javax.swing.JButton();
        jLabelsProductPreview = new javax.swing.JLabel();
        jTextField5 = new javax.swing.JTextField();
        jLabel28 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jPanelSalesInvoiceSearch = new javax.swing.JPanel();
        jScrollPane4 = new javax.swing.JScrollPane();
        jTable4 = new javax.swing.JTable();
        jButton2 = new javax.swing.JButton();
        jTextFieldSearchCustomerName1 = new javax.swing.JTextField();
        jTextFieldSearchCustomerPhone1 = new javax.swing.JTextField();
        jTextFieldSearchCustomerId1 = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jButton21 = new javax.swing.JButton();
        jButton22 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jButton23 = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        jButton26 = new javax.swing.JButton();
        jPanel11 = new javax.swing.JPanel();
        jButton24 = new javax.swing.JButton();
        jButton31 = new javax.swing.JButton();
        jButton32 = new javax.swing.JButton();
        jButton33 = new javax.swing.JButton();
        jTextField4 = new javax.swing.JTextField();
        jLabel24 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jTextField3 = new javax.swing.JTextField();
        jButton3 = new javax.swing.JButton();
        jScrollPane5 = new javax.swing.JScrollPane();
        jTable5 = new javax.swing.JTable();
        jPanel4 = new javax.swing.JPanel();
        jPanelMainSI1 = new javax.swing.JPanel();
        jScrollPane7 = new javax.swing.JScrollPane();
        jTableSalesInuiry1 = new javax.swing.JTable();
        jPanel7 = new javax.swing.JPanel();
        jLabel22 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jTextFieldCustomerId1 = new javax.swing.JTextField();
        jTextFieldCustomerName1 = new javax.swing.JTextField();
        jLabel29 = new javax.swing.JLabel();
        jLabel30 = new javax.swing.JLabel();
        jTextFieldSalesInquiryId1 = new javax.swing.JTextField();
        DatePickerSettings dateSettingsq = new DatePickerSettings();
        dateSettingsq.setFormatForDatesCommonEra("yyyy/MM/dd");
        dateSettingsq.setFormatForDatesBeforeCommonEra("uuuu/MM/dd");
        datePickerSalesInquiry1 = new com.github.lgooddatepicker.components.DatePicker(dateSettingsq);
        jButton19 = new javax.swing.JButton();
        jButton37 = new javax.swing.JButton();
        jButton38 = new javax.swing.JButton();
        jScrollPane8 = new javax.swing.JScrollPane();
        jTextAreaNote1 = new javax.swing.JTextArea();
        jLabel32 = new javax.swing.JLabel();
        jLabel33 = new javax.swing.JLabel();
        jTextFieldTotal1 = new javax.swing.JTextField();
        jLabel34 = new javax.swing.JLabel();
        jButton39 = new javax.swing.JButton();
        jLabel35 = new javax.swing.JLabel();
        jTextFieldGrandTotal1 = new javax.swing.JTextField();
        jComboBoxDiscountRate1 = new javax.swing.JComboBox<>();
        jButton40 = new javax.swing.JButton();
        jPanelproductSearch1 = new javax.swing.JPanel();
        jScrollPane9 = new javax.swing.JScrollPane();
        jTablesProduct1 = new javax.swing.JTable();
        jButton41 = new javax.swing.JButton();
        jTextFieldsDesignId1 = new javax.swing.JTextField();
        jTextFieldsProductType1 = new javax.swing.JTextField();
        jTextFieldsProductId1 = new javax.swing.JTextField();
        jLabel36 = new javax.swing.JLabel();
        jLabel37 = new javax.swing.JLabel();
        jLabel38 = new javax.swing.JLabel();
        jButton42 = new javax.swing.JButton();
        jButton43 = new javax.swing.JButton();
        jButton44 = new javax.swing.JButton();
        jButton45 = new javax.swing.JButton();
        jLabelsProductPreview1 = new javax.swing.JLabel();
        jButton46 = new javax.swing.JButton();

        setResizable(true);
        setTitle("Sales Invoice Management");
        setMaximumSize(new java.awt.Dimension(1365, 620));
        setMinimumSize(new java.awt.Dimension(1365, 620));
        setPreferredSize(new java.awt.Dimension(1365, 620));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTabbedPane1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jTabbedPane1.setName(""); // NOI18N

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel2.setMaximumSize(new java.awt.Dimension(1310, 530));
        jPanel2.setMinimumSize(new java.awt.Dimension(1310, 530));
        jPanel2.setPreferredSize(new java.awt.Dimension(1310, 530));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTableSalesInvoice.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Product ID", "Product Name", "Price", "Quantity Available","Quantity","SubTotal"
            }
        ));
        jScrollPane1.setViewportView(jTableSalesInvoice);

        jPanel2.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 170, 1140, 200));

        jPanel6.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel6.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton6.setText("Reset All");
        jButton6.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        jPanel6.add(jButton6, new org.netbeans.lib.awtextra.AbsoluteConstraints(990, 60, 120, -1));

        jLabel3.setText("Customer ID");
        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jPanel6.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 30, -1, -1));

        jLabel4.setText("Customer Name");
        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jPanel6.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 60, -1, -1));

        jTextFieldCustomerID.setEditable(false);
        jTextFieldCustomerID.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jTextFieldCustomerID.setName("Customer Name"); // NOI18N
        jPanel6.add(jTextFieldCustomerID, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 30, 140, -1));

        jTextFieldCustomerName.setEditable(false);
        jTextFieldCustomerName.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jTextFieldCustomerName.setName("Customer name"); // NOI18N
        jPanel6.add(jTextFieldCustomerName, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 60, 140, -1));

        jLabel2.setText("Sales Invoice  ID");
        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jPanel6.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 30, -1, -1));

        jLabel7.setText("Date");
        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jPanel6.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 60, -1, -1));

        jTextFieldSalesInvoiceId.setEditable(false);
        jTextFieldSalesInvoiceId.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jTextFieldSalesInvoiceId.setName("Sales Invoice ID"); // NOI18N
        jTextFieldSalesInvoiceId.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldSalesInvoiceIdActionPerformed(evt);
            }
        });
        jPanel6.add(jTextFieldSalesInvoiceId, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 30, 110, -1));

        datePickerSalesInvoice.setEnabled(false);
        datePickerSalesInvoice.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        datePickerSalesInvoice.setName(""); // NOI18N
        jPanel6.add(datePickerSalesInvoice, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 60, -1, -1));

        jButton11.setText("Search Customer");
        jButton11.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton11ActionPerformed(evt);
            }
        });
        jPanel6.add(jButton11, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 30, 150, -1));

        jLabel5.setText("Sales Inquiry ID");
        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jPanel6.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 90, -1, -1));

        jTextFieldSalesInquiryId.setEditable(false);
        jTextFieldSalesInquiryId.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jTextFieldSalesInquiryId.setName("Sales Inquiry ID"); // NOI18N
        jPanel6.add(jTextFieldSalesInquiryId, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 90, 140, -1));

        jButton12.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton12.setText("Search Sales Inquiry");
        jButton12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton12ActionPerformed(evt);
            }
        });
        jPanel6.add(jButton12, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 90, -1, -1));

        jPanel2.add(jPanel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 20, 1140, 130));

        jButtonADD.setText("ADD Sales Invoice");
        jButtonADD.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButtonADD.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonADDActionPerformed(evt);
            }
        });
        jPanel2.add(jButtonADD, new org.netbeans.lib.awtextra.AbsoluteConstraints(1140, 483, -1, 30));

        jButton13.setText("Add");
        jButton13.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton13.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton13ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton13, new org.netbeans.lib.awtextra.AbsoluteConstraints(1200, 240, 80, -1));

        jButton18.setText("Delete");
        jButton18.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton18.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton18ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton18, new org.netbeans.lib.awtextra.AbsoluteConstraints(1200, 280, 80, -1));

        jTextFieldTotal.setEditable(false);
        jTextFieldTotal.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jPanel2.add(jTextFieldTotal, new org.netbeans.lib.awtextra.AbsoluteConstraints(920, 390, 110, -1));

        jLabel26.setText("Total ");
        jLabel26.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jPanel2.add(jLabel26, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 390, -1, -1));

        jTextFieldGrandTotal.setEditable(false);
        jTextFieldGrandTotal.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jPanel2.add(jTextFieldGrandTotal, new org.netbeans.lib.awtextra.AbsoluteConstraints(920, 450, 110, -1));

        jLabel23.setText("Grand Total");
        jLabel23.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jPanel2.add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 450, 90, 20));

        jLabel27.setText("Discount Rate");
        jLabel27.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jPanel2.add(jLabel27, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 420, 100, 20));

        jComboBoxDiscountRate.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] {"","2.5", "5", "7.5", "10","12.5","15" }));
        jComboBoxDiscountRate.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jPanel2.add(jComboBoxDiscountRate, new org.netbeans.lib.awtextra.AbsoluteConstraints(920, 420, 110, -1));

        jButton36.setText("Calculate Total");
        jButton36.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton36.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton36ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton36, new org.netbeans.lib.awtextra.AbsoluteConstraints(1050, 390, -1, -1));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 1310, 530));

        jPanelcustomerSearch1.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanelcustomerSearch1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTableSCustomer.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jTableSCustomer.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTableSCustomerMouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(jTableSCustomer);

        jPanelcustomerSearch1.add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 140, 970, 310));

        jButton14.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton14.setText("Select");
        jButton14.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton14ActionPerformed(evt);
            }
        });
        jPanelcustomerSearch1.add(jButton14, new org.netbeans.lib.awtextra.AbsoluteConstraints(900, 470, -1, -1));

        jTextField10.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jTextField10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField10ActionPerformed(evt);
            }
        });
        jPanelcustomerSearch1.add(jTextField10, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 60, 160, -1));

        jTextField11.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jPanelcustomerSearch1.add(jTextField11, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 100, 160, -1));

        jTextFieldSDICustomerId.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jPanelcustomerSearch1.add(jTextFieldSDICustomerId, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 20, 160, -1));

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel12.setText("Customer ID");
        jPanelcustomerSearch1.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 20, -1, -1));

        jLabel14.setText("Customer Name");
        jLabel14.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jPanelcustomerSearch1.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 60, -1, -1));

        jLabel19.setText("Customer Phone");
        jLabel19.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jPanelcustomerSearch1.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 100, -1, -1));

        jButton15.setText("Search");
        jButton15.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton15.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton15ActionPerformed(evt);
            }
        });
        jPanelcustomerSearch1.add(jButton15, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 100, 80, -1));

        jButton16.setText("Search");
        jButton16.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton16.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton16ActionPerformed(evt);
            }
        });
        jPanelcustomerSearch1.add(jButton16, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 20, 80, -1));

        jButton17.setText("Search");
        jButton17.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton17.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton17ActionPerformed(evt);
            }
        });
        jPanelcustomerSearch1.add(jButton17, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 60, 80, -1));

        jButton20.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton20.setText("View All");
        jButton20.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton20ActionPerformed(evt);
            }
        });
        jPanelcustomerSearch1.add(jButton20, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 100, 110, -1));

        jPanel1.add(jPanelcustomerSearch1, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 20, 1020, 530));

        jPanelSalesInquirySearch.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanelSalesInquirySearch.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTablesSalesInquiry.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jTablesSalesInquiry.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTablesSalesInquiryMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(jTablesSalesInquiry);

        jPanelSalesInquirySearch.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 150, 960, 300));

        jButton1.setText("Search");
        jButton1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanelSalesInquirySearch.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 110, 110, -1));

        jTextFieldSearchCustomerName.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jTextFieldSearchCustomerName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldSearchCustomerNameActionPerformed(evt);
            }
        });
        jPanelSalesInquirySearch.add(jTextFieldSearchCustomerName, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 50, 150, -1));

        jTextFieldSearchCustomerPhone.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jPanelSalesInquirySearch.add(jTextFieldSearchCustomerPhone, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 80, 150, -1));

        jTextFieldSearchCustomerId.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jPanelSalesInquirySearch.add(jTextFieldSearchCustomerId, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 20, 150, -1));

        jLabel9.setText("Customer ID");
        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jPanelSalesInquirySearch.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, -1, -1));

        jLabel10.setText("Customer name");
        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jPanelSalesInquirySearch.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 50, -1, -1));

        jLabel11.setText("Customer phone");
        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jPanelSalesInquirySearch.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 80, -1, -1));

        jButton8.setText("View All");
        jButton8.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });
        jPanelSalesInquirySearch.add(jButton8, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 50, 120, -1));

        jButton9.setText("Reset All");
        jButton9.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton9ActionPerformed(evt);
            }
        });
        jPanelSalesInquirySearch.add(jButton9, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 80, 120, -1));

        jButton5.setText("Search");
        jButton5.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        jPanelSalesInquirySearch.add(jButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 20, 110, -1));

        jButton10.setText("Search");
        jButton10.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton10ActionPerformed(evt);
            }
        });
        jPanelSalesInquirySearch.add(jButton10, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 50, 110, -1));

        jLabel6.setText("Sales Inquiry ID");
        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jPanelSalesInquirySearch.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 110, -1, -1));

        jTextField1.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jPanelSalesInquirySearch.add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 110, 150, -1));

        jButton25.setText("Search");
        jButton25.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton25.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton25ActionPerformed(evt);
            }
        });
        jPanelSalesInquirySearch.add(jButton25, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 80, 110, -1));

        jButton35.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton35.setText("Select");
        jButton35.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton35ActionPerformed(evt);
            }
        });
        jPanelSalesInquirySearch.add(jButton35, new org.netbeans.lib.awtextra.AbsoluteConstraints(879, 470, 80, -1));

        jPanel1.add(jPanelSalesInquirySearch, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 20, 1020, 530));

        jPanelproductSearch.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanelproductSearch.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTablesProduct.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jTablesProduct.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTablesProductMouseClicked(evt);
            }
        });
        jScrollPane6.setViewportView(jTablesProduct);

        jPanelproductSearch.add(jScrollPane6, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 200, 920, 200));

        jButton27.setText("Select");
        jButton27.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton27.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton27ActionPerformed(evt);
            }
        });
        jPanelproductSearch.add(jButton27, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 420, 100, 30));

        jTextField12.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jTextField12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField12ActionPerformed(evt);
            }
        });
        jPanelproductSearch.add(jTextField12, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 90, 130, -1));

        jTextField13.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jPanelproductSearch.add(jTextField13, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 130, 130, -1));

        jTextFieldSDIpprId1.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jPanelproductSearch.add(jTextFieldSDIpprId1, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 50, 130, -1));

        jLabel18.setText("Product ID");
        jLabel18.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jPanelproductSearch.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 50, -1, -1));

        jLabel20.setText("Design ID");
        jLabel20.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jPanelproductSearch.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 90, -1, -1));

        jLabel21.setText("Product Type");
        jLabel21.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jPanelproductSearch.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 130, -1, -1));

        jButton28.setText("Search");
        jButton28.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton28.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton28ActionPerformed(evt);
            }
        });
        jPanelproductSearch.add(jButton28, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 130, -1, -1));

        jButton29.setText("Search");
        jButton29.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton29.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton29ActionPerformed(evt);
            }
        });
        jPanelproductSearch.add(jButton29, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 50, -1, -1));

        jButton30.setText("Search");
        jButton30.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton30.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton30ActionPerformed(evt);
            }
        });
        jPanelproductSearch.add(jButton30, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 90, -1, -1));

        jButton34.setText("View All");
        jButton34.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton34.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton34ActionPerformed(evt);
            }
        });
        jPanelproductSearch.add(jButton34, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 130, 100, -1));

        jLabelsProductPreview.setText("             Product Preview");
        jPanelproductSearch.add(jLabelsProductPreview, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 30, 210, 150));
        jPanelproductSearch.add(jTextField5, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 430, 90, -1));

        jLabel28.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel28.setText("Quantity");
        jPanelproductSearch.add(jLabel28, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 430, -1, 20));

        jPanel1.add(jPanelproductSearch, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 20, 1020, 530));

        jTabbedPane1.addTab("ADD Sales Invoice", jPanel1);

        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanelSalesInvoiceSearch.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanelSalesInvoiceSearch.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTable4.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jTable4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable4MouseClicked(evt);
            }
        });
        jScrollPane4.setViewportView(jTable4);

        jPanelSalesInvoiceSearch.add(jScrollPane4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 150, 980, 220));

        jButton2.setText("Search");
        jButton2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanelSalesInvoiceSearch.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 110, 90, -1));

        jTextFieldSearchCustomerName1.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jTextFieldSearchCustomerName1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldSearchCustomerName1ActionPerformed(evt);
            }
        });
        jPanelSalesInvoiceSearch.add(jTextFieldSearchCustomerName1, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 50, 150, -1));

        jTextFieldSearchCustomerPhone1.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jPanelSalesInvoiceSearch.add(jTextFieldSearchCustomerPhone1, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 80, 150, -1));

        jTextFieldSearchCustomerId1.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jPanelSalesInvoiceSearch.add(jTextFieldSearchCustomerId1, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 20, 150, -1));

        jLabel13.setText("Customer ID");
        jLabel13.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jPanelSalesInvoiceSearch.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, -1, -1));

        jLabel15.setText("Customer Name");
        jLabel15.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jPanelSalesInvoiceSearch.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 50, -1, -1));

        jLabel16.setText("Customer phone");
        jLabel16.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jPanelSalesInvoiceSearch.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 80, -1, -1));

        jButton21.setText("View All");
        jButton21.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton21.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton21ActionPerformed(evt);
            }
        });
        jPanelSalesInvoiceSearch.add(jButton21, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 60, 90, -1));

        jButton22.setText("Reset All");
        jButton22.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton22.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton22ActionPerformed(evt);
            }
        });
        jPanelSalesInvoiceSearch.add(jButton22, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 90, 90, -1));

        jButton7.setText("Search");
        jButton7.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });
        jPanelSalesInvoiceSearch.add(jButton7, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 20, 90, -1));

        jButton23.setText("Search");
        jButton23.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton23.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton23ActionPerformed(evt);
            }
        });
        jPanelSalesInvoiceSearch.add(jButton23, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 50, 90, -1));

        jLabel8.setText("Sales Inquiry ID");
        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jPanelSalesInvoiceSearch.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 110, -1, -1));

        jTextField2.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jPanelSalesInvoiceSearch.add(jTextField2, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 110, 150, -1));

        jButton26.setText("Search");
        jButton26.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton26.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton26ActionPerformed(evt);
            }
        });
        jPanelSalesInvoiceSearch.add(jButton26, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 80, 90, -1));

        jPanel11.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel11.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton24.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton24.setText("Report");
        jPanel11.add(jButton24, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 90, 110, -1));

        jButton31.setText("Edit");
        jButton31.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton31.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton31ActionPerformed(evt);
            }
        });
        jPanel11.add(jButton31, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 60, 110, -1));

        jButton32.setText("Delete");
        jButton32.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton32.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton32ActionPerformed(evt);
            }
        });
        jPanel11.add(jButton32, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 120, 110, -1));

        jButton33.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton33.setText("Clear");
        jPanel11.add(jButton33, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 150, 110, -1));

        jTextField4.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jPanel11.add(jTextField4, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 30, 110, -1));

        jLabel24.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel24.setText("Sales  Invoice ID");
        jPanel11.add(jLabel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 30, -1, -1));

        jPanelSalesInvoiceSearch.add(jPanel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(1030, 20, 250, 190));

        jLabel17.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel17.setText("Sales Invoice ID");
        jPanelSalesInvoiceSearch.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 30, -1, -1));

        jTextField3.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jPanelSalesInvoiceSearch.add(jTextField3, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 30, 140, -1));

        jButton3.setText("Search");
        jButton3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanelSalesInvoiceSearch.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 30, 90, -1));

        jTable5.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane5.setViewportView(jTable5);

        jPanelSalesInvoiceSearch.add(jScrollPane5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 390, 980, 130));

        jPanel3.add(jPanelSalesInvoiceSearch, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 20, 1290, 530));

        jTabbedPane1.addTab("Search &  Delete", jPanel3);

        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanelMainSI1.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanelMainSI1.setToolTipText("");
        jPanelMainSI1.setMaximumSize(new java.awt.Dimension(1310, 530));
        jPanelMainSI1.setMinimumSize(new java.awt.Dimension(1310, 530));
        jPanelMainSI1.setPreferredSize(new java.awt.Dimension(1310, 530));
        jPanelMainSI1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTableSalesInuiry1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Product ID", "Product Name", "Price", "Quantity","SubTotal"
            }
        ));
        jTableSalesInuiry1.addContainerListener(new java.awt.event.ContainerAdapter() {
            public void componentAdded(java.awt.event.ContainerEvent evt) {
                jTableSalesInuiry1ComponentAdded(evt);
            }
        });
        jTableSalesInuiry1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTableSalesInuiry1MouseClicked(evt);
            }
        });
        jTableSalesInuiry1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTableSalesInuiry1KeyTyped(evt);
            }
        });
        jScrollPane7.setViewportView(jTableSalesInuiry1);

        jPanelMainSI1.add(jScrollPane7, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 140, 1110, 200));

        jPanel7.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        jPanel7.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel22.setText("Customer ID");
        jLabel22.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jPanel7.add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 20, -1, -1));

        jLabel25.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel25.setText("Customer Name");
        jPanel7.add(jLabel25, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 50, -1, -1));

        jTextFieldCustomerId1.setEditable(false);
        jTextFieldCustomerId1.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jTextFieldCustomerId1.setName("Customer Name"); // NOI18N
        jTextFieldCustomerId1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldCustomerId1ActionPerformed(evt);
            }
        });
        jPanel7.add(jTextFieldCustomerId1, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 20, 110, -1));

        jTextFieldCustomerName1.setEditable(false);
        jTextFieldCustomerName1.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jTextFieldCustomerName1.setName("Company name"); // NOI18N
        jPanel7.add(jTextFieldCustomerName1, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 50, 110, -1));

        jLabel29.setText("Sales Inquiry ID");
        jLabel29.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jPanel7.add(jLabel29, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, -1, -1));

        jLabel30.setText("Date");
        jLabel30.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jPanel7.add(jLabel30, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 50, -1, -1));

        jTextFieldSalesInquiryId1.setEditable(false);
        jTextFieldSalesInquiryId1.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jTextFieldSalesInquiryId1.setName("Customer ID"); // NOI18N
        jTextFieldSalesInquiryId1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldSalesInquiryId1ActionPerformed(evt);
            }
        });
        jPanel7.add(jTextFieldSalesInquiryId1, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 20, 110, -1));

        datePickerSalesInquiry1.setEnabled(false);
        datePickerSalesInquiry1.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        datePickerSalesInquiry1.setName(""); // NOI18N
        jPanel7.add(datePickerSalesInquiry1, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 50, -1, -1));

        jPanelMainSI1.add(jPanel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 20, 1200, 100));

        jButton19.setText("Cancel Editing");
        jButton19.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton19.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton19ActionPerformed(evt);
            }
        });
        jPanelMainSI1.add(jButton19, new org.netbeans.lib.awtextra.AbsoluteConstraints(960, 480, 140, 30));

        jButton37.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton37.setText("Add");
        jButton37.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton37ActionPerformed(evt);
            }
        });
        jPanelMainSI1.add(jButton37, new org.netbeans.lib.awtextra.AbsoluteConstraints(1180, 200, 80, -1));

        jButton38.setText("Delete");
        jButton38.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton38.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton38ActionPerformed(evt);
            }
        });
        jPanelMainSI1.add(jButton38, new org.netbeans.lib.awtextra.AbsoluteConstraints(1180, 240, 80, -1));

        jTextAreaNote1.setColumns(20);
        jTextAreaNote1.setEditable(false);
        jTextAreaNote1.setRows(5);
        jTextAreaNote1.setFont(new java.awt.Font("Monospaced", 0, 12)); // NOI18N
        jScrollPane8.setViewportView(jTextAreaNote1);

        jPanelMainSI1.add(jScrollPane8, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 360, 500, 130));

        jLabel32.setText("Note");
        jLabel32.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jPanelMainSI1.add(jLabel32, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 370, -1, -1));

        jLabel33.setText("Total ");
        jLabel33.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jPanelMainSI1.add(jLabel33, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 370, -1, -1));

        jTextFieldTotal1.setEditable(false);
        jTextFieldTotal1.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jPanelMainSI1.add(jTextFieldTotal1, new org.netbeans.lib.awtextra.AbsoluteConstraints(940, 370, 100, -1));

        jLabel34.setText("Discount Rate");
        jLabel34.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jPanelMainSI1.add(jLabel34, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 400, 110, 20));

        jButton39.setText("Calculate Total");
        jButton39.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton39.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton39ActionPerformed(evt);
            }
        });
        jPanelMainSI1.add(jButton39, new org.netbeans.lib.awtextra.AbsoluteConstraints(1110, 370, 140, -1));

        jLabel35.setText("Grand Total");
        jLabel35.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jPanelMainSI1.add(jLabel35, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 430, 100, 20));

        jTextFieldGrandTotal1.setEditable(false);
        jTextFieldGrandTotal1.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jPanelMainSI1.add(jTextFieldGrandTotal1, new org.netbeans.lib.awtextra.AbsoluteConstraints(940, 430, 100, -1));

        jComboBoxDiscountRate1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] {"","2.5", "5", "7.5", "10","12.5","15" }));
        jComboBoxDiscountRate1.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jPanelMainSI1.add(jComboBoxDiscountRate1, new org.netbeans.lib.awtextra.AbsoluteConstraints(940, 400, 100, -1));

        jButton40.setText("Edit Invoice ");
        jButton40.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton40.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton40ActionPerformed(evt);
            }
        });
        jPanelMainSI1.add(jButton40, new org.netbeans.lib.awtextra.AbsoluteConstraints(1130, 480, 140, 30));

        jPanel4.add(jPanelMainSI1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 1310, 530));

        jPanelproductSearch1.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        jPanelproductSearch1.setMaximumSize(new java.awt.Dimension(1020, 530));
        jPanelproductSearch1.setMinimumSize(new java.awt.Dimension(1020, 530));
        jPanelproductSearch1.setPreferredSize(new java.awt.Dimension(1020, 530));
        jPanelproductSearch1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTablesProduct1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jTablesProduct1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTablesProduct1MouseClicked(evt);
            }
        });
        jScrollPane9.setViewportView(jTablesProduct1);

        jPanelproductSearch1.add(jScrollPane9, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 210, 950, 250));

        jButton41.setText("Select");
        jButton41.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton41.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton41ActionPerformed(evt);
            }
        });
        jPanelproductSearch1.add(jButton41, new org.netbeans.lib.awtextra.AbsoluteConstraints(879, 483, 90, 30));

        jTextFieldsDesignId1.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jTextFieldsDesignId1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldsDesignId1ActionPerformed(evt);
            }
        });
        jPanelproductSearch1.add(jTextFieldsDesignId1, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 90, 100, -1));

        jTextFieldsProductType1.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jPanelproductSearch1.add(jTextFieldsProductType1, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 130, 100, -1));

        jTextFieldsProductId1.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jPanelproductSearch1.add(jTextFieldsProductId1, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 50, 100, -1));

        jLabel36.setText("Product ID");
        jLabel36.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jPanelproductSearch1.add(jLabel36, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 50, -1, -1));

        jLabel37.setText("Design ID");
        jLabel37.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jPanelproductSearch1.add(jLabel37, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 90, -1, -1));

        jLabel38.setText("Product Type");
        jLabel38.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jPanelproductSearch1.add(jLabel38, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 130, -1, -1));

        jButton42.setText("Search");
        jButton42.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton42.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton42ActionPerformed(evt);
            }
        });
        jPanelproductSearch1.add(jButton42, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 130, 90, -1));

        jButton43.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton43.setText("Search");
        jButton43.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton43ActionPerformed(evt);
            }
        });
        jPanelproductSearch1.add(jButton43, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 50, 90, -1));

        jButton44.setText("Search");
        jButton44.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton44.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton44ActionPerformed(evt);
            }
        });
        jPanelproductSearch1.add(jButton44, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 90, 90, -1));

        jButton45.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton45.setText("View All");
        jButton45.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton45ActionPerformed(evt);
            }
        });
        jPanelproductSearch1.add(jButton45, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 70, 100, -1));

        jLabelsProductPreview1.setText("              Product Preview");
        jPanelproductSearch1.add(jLabelsProductPreview1, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 20, 240, 170));

        jButton46.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton46.setText("Reset ALL");
        jButton46.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton46ActionPerformed(evt);
            }
        });
        jPanelproductSearch1.add(jButton46, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 110, 100, -1));

        jPanel4.add(jPanelproductSearch1, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 20, 1020, 530));

        jTabbedPane1.addTab("", jPanel4);

        getContentPane().add(jTabbedPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1350, 590));

        getAccessibleContext().setAccessibleName("");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed

    }//GEN-LAST:event_jButton6ActionPerformed

    private void jTextFieldSalesInvoiceIdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldSalesInvoiceIdActionPerformed

    }//GEN-LAST:event_jTextFieldSalesInvoiceIdActionPerformed

    private void jButton11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton11ActionPerformed
        jPanelcustomerSearch1.setVisible(true);
        jPanelSalesInquirySearch.setVisible(false);
        jPanelproductSearch.setVisible(false);   
        jPanel2.setVisible(false);
    }//GEN-LAST:event_jButton11ActionPerformed

    private void jButtonADDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonADDActionPerformed
         boolean result=salesinvoicemodel.AddSIN(jTextFieldSalesInvoiceId,jTextFieldCustomerID,jTextFieldSalesInquiryId,datePickerSalesInvoice,jTextFieldTotal,jComboBoxDiscountRate,jTextFieldGrandTotal,jTableSalesInvoice);
        if(result){
            JOptionPane.showMessageDialog(null,"Successfully To Added Sales Invoice", "InfoBox", JOptionPane.INFORMATION_MESSAGE);
             
            salesinvoicemodel.generate_sin();
                
              CC();
              CS();
              ProductModel.setRowCount(0);
        }
        else{
            JOptionPane.showMessageDialog(null,"Failed To Added Sales Invoice", "InfoBox", JOptionPane.INFORMATION_MESSAGE);
        
        } 
    }//GEN-LAST:event_jButtonADDActionPerformed

    private void jButton13ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton13ActionPerformed
        jPanelcustomerSearch1.setVisible(false);
        jPanelSalesInquirySearch.setVisible(false);
        jPanelproductSearch.setVisible(true);
        jPanel2.setVisible(false);
    }//GEN-LAST:event_jButton13ActionPerformed

    private void jButton12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton12ActionPerformed
        jPanelcustomerSearch1.setVisible(false);
        jPanelSalesInquirySearch.setVisible(true);
        jPanelproductSearch.setVisible(false);
        jPanel2.setVisible(false);
         
    }//GEN-LAST:event_jButton12ActionPerformed

    private void jTableSCustomerMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTableSCustomerMouseClicked
    
    int x=jTableSCustomer.getSelectedRow();
    String y=(String) jTableSCustomer.getValueAt(x,0);
    
    AutoDB_Connect.DB_ResultSet = autoSqlQuery.executeAutoSearchAll("d_customer_table","CustomerId", y);
    
    try {
        AutoDB_Connect.DB_ResultSet.next();
        CustomerId=AutoDB_Connect.DB_ResultSet.getString("CustomerId");
        CustomerName=AutoDB_Connect.DB_ResultSet.getString("Name");

        
       
    } catch (SQLException ex) {
        Logger.getLogger(Customer.class.getName()).log(Level.SEVERE, null, ex);
    }    
    }//GEN-LAST:event_jTableSCustomerMouseClicked

    private void jButton14ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton14ActionPerformed
        jPanelcustomerSearch1.setVisible(false);
        jPanelSalesInquirySearch.setVisible(false);
        jPanelproductSearch.setVisible(false);
        jPanel2.setVisible(true);
        jTextFieldCustomerID.setText(CustomerId);
        jTextFieldCustomerName.setText(CustomerName);
    
    }//GEN-LAST:event_jButton14ActionPerformed

    private void jTextField10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField10ActionPerformed
       
    }//GEN-LAST:event_jTextField10ActionPerformed

    private void jButton16ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton16ActionPerformed
    jTableSCustomer.setModel(DbUtils.resultSetToTableModel(salesinvoicemodel.SearchID(jTextFieldSDICustomerId.getText())));
    }//GEN-LAST:event_jButton16ActionPerformed

    private void jButton20ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton20ActionPerformed
    jTableSCustomer.setModel(DbUtils.resultSetToTableModel(salesinvoicemodel.ViewAllCustomer()));       
    }//GEN-LAST:event_jButton20ActionPerformed

    private void jTablesSalesInquiryMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTablesSalesInquiryMouseClicked
            
    int x=jTablesSalesInquiry.getSelectedRow();
    String y=(String) jTablesSalesInquiry.getValueAt(x,0);
    SalesInquriyId=y;
    //DB_Connect.DB_ResultSet = autoSqlQuery.executeAutoSearchAll("d_salesInquiry_table","CustomerId", y);
    
    //try {
       // DB_Connect.DB_ResultSet.next();
       // CustomerId=DB_Connect.DB_ResultSet.getString("CustomerId");
        //CustomerName=DB_Connect.DB_ResultSet.getString("CustomerName");

        
       
   // } catch (SQLException ex) {
     //   Logger.getLogger(Customer.class.getName()).log(Level.SEVERE, null, ex);
    //}    
    }//GEN-LAST:event_jTablesSalesInquiryMouseClicked

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed

    }//GEN-LAST:event_jButton1ActionPerformed

    private void jTextFieldSearchCustomerNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldSearchCustomerNameActionPerformed

    }//GEN-LAST:event_jTextFieldSearchCustomerNameActionPerformed

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
    jTablesSalesInquiry.setModel(DbUtils.resultSetToTableModel(salesinvoicemodel.ViewAllInquiry()));       
    }//GEN-LAST:event_jButton8ActionPerformed

    private void jButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton9ActionPerformed

    }//GEN-LAST:event_jButton9ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed

    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton10ActionPerformed

    }//GEN-LAST:event_jButton10ActionPerformed

    private void jButton25ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton25ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton25ActionPerformed

    private void jTable4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable4MouseClicked
        int x=jTable4.getSelectedRow();
        String y=(String) jTable4.getValueAt(x,0);
        jTextField4.setText(y);

        AutoDB_Connect.DB_ResultSet = autoSqlQuery.executeAutoSearchAll("d_salesInvoice_table1","salesInvoiceId", y);
        jTable5.setModel(DbUtils.resultSetToTableModel(AutoDB_Connect.DB_ResultSet));
    }//GEN-LAST:event_jTable4MouseClicked

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        jTable4.setModel(DbUtils.resultSetToTableModel(salesinvoicemodel.SearchSII(jTextField2.getText())));
        CC();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jTextFieldSearchCustomerName1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldSearchCustomerName1ActionPerformed

    }//GEN-LAST:event_jTextFieldSearchCustomerName1ActionPerformed

    private void jButton21ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton21ActionPerformed
         jTable4.setModel(DbUtils.resultSetToTableModel(salesinvoicemodel.ViewAllInquiry()));
        CC();
    }//GEN-LAST:event_jButton21ActionPerformed

    private void jButton22ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton22ActionPerformed
CC();
    }//GEN-LAST:event_jButton22ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        jTable4.setModel(DbUtils.resultSetToTableModel(salesinvoicemodel.SearchCustomerID(jTextFieldSearchCustomerId1.getText())));
        CC();
    }//GEN-LAST:event_jButton7ActionPerformed

    private void jButton23ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton23ActionPerformed
    jTable4.setModel(DbUtils.resultSetToTableModel(salesinvoicemodel.SearchCustomerName(jTextFieldSearchCustomerName1.getText())));
        
        CC();
    }//GEN-LAST:event_jButton23ActionPerformed

    private void jButton26ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton26ActionPerformed
        jTable4.setModel(DbUtils.resultSetToTableModel(salesinvoicemodel.SearchCusPhone(jTextFieldSearchCustomerPhone1.getText())));
        CC();
    }//GEN-LAST:event_jButton26ActionPerformed

    private void jButton31ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton31ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton31ActionPerformed

    private void jButton32ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton32ActionPerformed
       Boolean result =salesinvoicemodel.DeleteSII(jTextField4.getText());
        if(result){
            JOptionPane.showMessageDialog(null,"Successfully Deleted SINI", "InfoBox", JOptionPane.INFORMATION_MESSAGE);
         //   clear();
            CC();
            clearTable();
        }
        else{
            JOptionPane.showMessageDialog(null,"Failed Deleted SINI", "InfoBox", JOptionPane.INFORMATION_MESSAGE);

        }
        CC();
 
    }//GEN-LAST:event_jButton32ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
     jTable4.setModel(DbUtils.resultSetToTableModel(salesinvoicemodel.SearchSInI(jTextField2.getText())));
        CC();
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jTablesProductMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTablesProductMouseClicked
        
    int x=jTablesProduct.getSelectedRow();
    String y=(String) jTablesProduct.getValueAt(x,0);
    
    AutoDB_Connect.DB_ResultSet = autoSqlQuery.executeAutoSearchAll("product_table","ProductId", y);
    
    try {
        AutoDB_Connect.DB_ResultSet.next();
        ProductID=AutoDB_Connect.DB_ResultSet.getString("ProductId");
        ProductName=AutoDB_Connect.DB_ResultSet.getString("ProductName");
        Price=AutoDB_Connect.DB_ResultSet.getString("Price");
        Quantity=AutoDB_Connect.DB_ResultSet.getString("Quantity");
        
    } catch (SQLException ex) {
        Logger.getLogger(Customer.class.getName()).log(Level.SEVERE, null, ex);
    }    
    jLabelsProductPreview.setIcon(autoSqlQuery.executeAutoGetImage(ProductID));
    }//GEN-LAST:event_jTablesProductMouseClicked

    private void jButton27ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton27ActionPerformed
        int Q=Integer.parseInt(Quantity);
        int W=Integer.parseInt(jTextField5.getText());
        if(W<Q){
        ProductModel.addRow(new Object[]{ ProductID,ProductName,Price,Quantity,jTextField5.getText()});
        jPanelproductSearch.setVisible(false);
        jPanel2.setVisible(true);
        jTextField1.setText("");
        }
        else
        {
        JOptionPane.showMessageDialog(null,"Exceed Stock Quantitiy", "InfoBox", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_jButton27ActionPerformed

    private void jTextField12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField12ActionPerformed

    }//GEN-LAST:event_jTextField12ActionPerformed

    private void jButton29ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton29ActionPerformed
        jTablesProduct.setModel(DbUtils.resultSetToTableModel(autoSqlQuery.executeAutoSearchAll("product_table","ProductId",jTextFieldSDIpprId1.getText())));
    }//GEN-LAST:event_jButton29ActionPerformed

    private void jButton34ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton34ActionPerformed
   jTablesProduct.setModel(DbUtils.resultSetToTableModel(salesinvoicemodel.ViewAllProducts()));
    }//GEN-LAST:event_jButton34ActionPerformed

    private void jButton35ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton35ActionPerformed
        jPanelcustomerSearch1.setVisible(false);
        jPanelSalesInquirySearch.setVisible(false);
        jPanelproductSearch.setVisible(false);
        jPanel2.setVisible(true);
        jTextFieldSalesInquiryId.setText(SalesInquriyId);
    }//GEN-LAST:event_jButton35ActionPerformed

    private void jButton36ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton36ActionPerformed

        getSubTotal();
        getTotal();
        getGrandTotal();
    }//GEN-LAST:event_jButton36ActionPerformed

    private void jButton18ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton18ActionPerformed
          ProductModel.removeRow(RowCountjTable1);
    }//GEN-LAST:event_jButton18ActionPerformed

    private void jButton17ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton17ActionPerformed
       jTableSCustomer.setModel(DbUtils.resultSetToTableModel(salesinvoicemodel.SearchCustomerTName(jTextField10.getText())));    
       // clearSearch();
    }//GEN-LAST:event_jButton17ActionPerformed

    private void jButton15ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton15ActionPerformed
     jTableSCustomer.setModel(DbUtils.resultSetToTableModel(salesinvoicemodel.SearchCustomerTPhone(jTextField11.getText())));    
        //clearSearch();
    }//GEN-LAST:event_jButton15ActionPerformed

    private void jButton30ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton30ActionPerformed
     jTablesProduct.setModel(DbUtils.resultSetToTableModel(autoSqlQuery.executeAutoSearchAll("product_table","DesignId",jTextField12.getText())));
    }//GEN-LAST:event_jButton30ActionPerformed

    private void jButton28ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton28ActionPerformed
     jTablesProduct.setModel(DbUtils.resultSetToTableModel(autoSqlQuery.executeAutoSearchAll("product_table","ProductType",jTextField13.getText())));
    }//GEN-LAST:event_jButton28ActionPerformed

    private void jTableSalesInuiry1ComponentAdded(java.awt.event.ContainerEvent evt) {//GEN-FIRST:event_jTableSalesInuiry1ComponentAdded
        // TODO add your handling code here:
    }//GEN-LAST:event_jTableSalesInuiry1ComponentAdded

    private void jTableSalesInuiry1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTableSalesInuiry1MouseClicked
      //  RowCountjTable1=jTableSalesInuiry.getSelectedRow();
    }//GEN-LAST:event_jTableSalesInuiry1MouseClicked

    private void jTableSalesInuiry1KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTableSalesInuiry1KeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_jTableSalesInuiry1KeyTyped

    private void jTextFieldCustomerId1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldCustomerId1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldCustomerId1ActionPerformed

    private void jTextFieldSalesInquiryId1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldSalesInquiryId1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldSalesInquiryId1ActionPerformed

    private void jButton19ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton19ActionPerformed
        jTabbedPane1.setSelectedIndex(1);

        CC();
        clearTable();
    }//GEN-LAST:event_jButton19ActionPerformed

    private void jButton37ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton37ActionPerformed
        jPanelproductSearch1.setVisible(true);
        jPanelMainSI1.setVisible(false);
    }//GEN-LAST:event_jButton37ActionPerformed

    private void jButton38ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton38ActionPerformed
       // ProductModel1.removeRow(RowCountjTable);
    }//GEN-LAST:event_jButton38ActionPerformed

    private void jButton39ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton39ActionPerformed
        getSubTotalE();
        getTotalE();
        getGrandTotalE();
    }//GEN-LAST:event_jButton39ActionPerformed

    private void jButton40ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton40ActionPerformed
        boolean result=salesinvoicemodel.EditSINI(jTextFieldSalesInquiryId1,jTextFieldCustomerId1,datePickerSalesInquiry1,jTextAreaNote1,jTextFieldTotal1,jComboBoxDiscountRate1,jTextFieldGrandTotal1,jTableSalesInuiry1);
        if(result){
            JOptionPane.showMessageDialog(null,"Successfully To Edit Invoice", "InfoBox", JOptionPane.INFORMATION_MESSAGE);
            jTabbedPane1.setSelectedIndex(1);


            CC();
            clearTable();
        }
        else{
            JOptionPane.showMessageDialog(null,"Failed To Edit Invoice", "InfoBox", JOptionPane.INFORMATION_MESSAGE);

        }

    }//GEN-LAST:event_jButton40ActionPerformed

    private void jTablesProduct1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTablesProduct1MouseClicked

        int x=jTablesProduct1.getSelectedRow();
        String y=(String) jTablesProduct1.getValueAt(x,0);

        AutoDB_Connect.DB_ResultSet = autoSqlQuery.executeAutoSearchAll("product_table","ProductId", y);

        try {
            AutoDB_Connect.DB_ResultSet.next();
            ProductID1=AutoDB_Connect.DB_ResultSet.getString("ProductId");
            ProductName1=AutoDB_Connect.DB_ResultSet.getString("ProductName");
            Price1=AutoDB_Connect.DB_ResultSet.getString("Price");
            //Quantity=DB_Connect.DB_ResultSet.getString("ProductId");

        } catch (SQLException ex) {
            Logger.getLogger(Customer.class.getName()).log(Level.SEVERE, null, ex);
        }
        jLabelsProductPreview1.setIcon(autoSqlQuery.executeAutoGetImage(ProductID1));
    }//GEN-LAST:event_jTablesProduct1MouseClicked

    private void jButton41ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton41ActionPerformed
        ProductModel1 = (DefaultTableModel) jTableSalesInuiry1.getModel();
        ProductModel1.addRow(new Object[]{jTextField4.getText(), ProductID1,Quantity1,Price1});
        jPanelproductSearch1.setVisible(false);
        jPanelMainSI1.setVisible(true);

    }//GEN-LAST:event_jButton41ActionPerformed

    private void jTextFieldsDesignId1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldsDesignId1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldsDesignId1ActionPerformed

    private void jButton42ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton42ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton42ActionPerformed

    private void jButton43ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton43ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton43ActionPerformed

    private void jButton44ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton44ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton44ActionPerformed

    private void jButton45ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton45ActionPerformed
        jTablesProduct1.setModel(DbUtils.resultSetToTableModel(autoSqlQuery.executeAutoViewAll("product_table")));
    }//GEN-LAST:event_jButton45ActionPerformed

    private void jButton46ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton46ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton46ActionPerformed
    
    
    public void CC(){
        jTextFieldSearchCustomerId1.setText("");
        jTextFieldCustomerID.setText("");
        jTextFieldSearchCustomerName1.setText("");
        jTextFieldSearchCustomerPhone1.setText("");
        jTextField2.setText("");
        jTextFieldCustomerName.setText("");
        jTextFieldSalesInquiryId.setText("");

    }
    
    public void getSubTotal(){
     
     double total = 0;
     double mut1 = 0;
     double mut2 = 0;
     String value1;
     String value2;
     int column1 = 2;
     int column2 = 4;

    for (int i = 0; i < ProductModel.getRowCount(); i++){
    if (ProductModel.getValueAt(i, column1) != null&&ProductModel.getValueAt(i, column2) != null)       
        {//System.out.println(ProductModel.getValueAt(i, column1));
        value1= (String) ProductModel.getValueAt(i, column1);
        value2= (String) ProductModel.getValueAt(i, column2);
        mut1=Double.valueOf(value1);
        mut2=Double.valueOf(value2);
        total= mut1*mut2;
        ProductModel.setValueAt(total, i, 5);
        }
    else {//error message box
        
    }
  
    }
    }
    
    public void getTotal(){
     
     double total = 0;
     double value;
     int column = 5; 

    for (int i = 0; i < ProductModel.getRowCount(); i++){
    if (ProductModel.getValueAt(i, column) != null)       
        {//System.out.println(ProductModel.getValueAt(i, column));
        value=  (double) ProductModel.getValueAt(i, column);
        total=total+value;
        } 
  
    }
    jTextFieldTotal.setText(String.valueOf(total));
    }
    
        public void getGrandTotal(){
     

    if (jComboBoxDiscountRate.getSelectedItem().equals("")){
        jTextFieldGrandTotal.setText(jTextFieldTotal.getText());
        } 
    else{
        double x=Double.valueOf(jTextFieldTotal.getText());
        double y=Double.valueOf(jComboBoxDiscountRate.getSelectedItem().toString());
        y=((100-y)/100);
        jTextFieldGrandTotal.setText(String.valueOf(x*y));
    }
  
    }
     public void getSubTotalE(){
     ProductModel1 = (DefaultTableModel) jTableSalesInuiry1.getModel();
     double total = 0;
     double mut1 = 0;
     double mut2 = 0;
     String value1;
     String value2;
     int column1 = 2;
     int column2 = 3;

    for (int i = 0; i < ProductModel1.getRowCount(); i++){
    if (ProductModel1.getValueAt(i, column1) != null&&ProductModel1.getValueAt(i, column2) != null)       
        {//System.out.println(ProductModel.getValueAt(i, column1));
        value1= (String) ProductModel1.getValueAt(i, column1);
        value2= (String) ProductModel1.getValueAt(i, column2);
        mut1=Double.valueOf(value1);
        mut2=Double.valueOf(value2);
        total= mut1*mut2;
        ProductModel1.setValueAt(total, i, 4);
        }
    else {//error message box
        
    }
  
    }
    }
        public void getTotalE(){
     ProductModel1 = (DefaultTableModel) jTableSalesInuiry1.getModel();
     double total = 0;
     double value;
     int column = 4; 

    for (int i = 0; i < ProductModel1.getRowCount(); i++){
    if (ProductModel1.getValueAt(i, column) != null)       
        {//System.out.println(ProductModel.getValueAt(i, column));
        value=  (double) ProductModel1.getValueAt(i, column);
        total=total+value;
        } 
  
    }
    jTextFieldTotal1.setText(String.valueOf(total));
    }
        
     public void getGrandTotalE(){
     

    if (jComboBoxDiscountRate1.getSelectedItem().equals("")){
        jTextFieldGrandTotal1.setText(jTextFieldTotal1.getText());
        } 
    else{
        double x=Double.valueOf(jTextFieldTotal1.getText());
        double y=Double.valueOf(jComboBoxDiscountRate1.getSelectedItem().toString());
        y=((100-y)/100);
        jTextFieldGrandTotal1.setText(String.valueOf(x*y));
    }}
    private void clearTable(){
    sedmodel1= (DefaultTableModel) jTable4.getModel();
    sedmodel1.getDataVector().removeAllElements();
    sedmodel1.fireTableDataChanged();
        
    sedmodel2 = (DefaultTableModel) jTable5.getModel();
    sedmodel2.getDataVector().removeAllElements();
    sedmodel2.fireTableDataChanged();
    
    }
    private void CS(){
        jTextFieldSearchCustomerId1.setText("");
        jTextFieldCustomerName.setText("");
        jTextFieldGrandTotal.setText("");
        jComboBoxDiscountRate.setSelectedIndex(0);
        jTextFieldTotal.setText("");
        



    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private com.github.lgooddatepicker.components.DatePicker datePickerSalesInquiry1;
    private com.github.lgooddatepicker.components.DatePicker datePickerSalesInvoice;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton10;
    private javax.swing.JButton jButton11;
    private javax.swing.JButton jButton12;
    private javax.swing.JButton jButton13;
    private javax.swing.JButton jButton14;
    private javax.swing.JButton jButton15;
    private javax.swing.JButton jButton16;
    private javax.swing.JButton jButton17;
    private javax.swing.JButton jButton18;
    private javax.swing.JButton jButton19;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton20;
    private javax.swing.JButton jButton21;
    private javax.swing.JButton jButton22;
    private javax.swing.JButton jButton23;
    private javax.swing.JButton jButton24;
    private javax.swing.JButton jButton25;
    private javax.swing.JButton jButton26;
    private javax.swing.JButton jButton27;
    private javax.swing.JButton jButton28;
    private javax.swing.JButton jButton29;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton30;
    private javax.swing.JButton jButton31;
    private javax.swing.JButton jButton32;
    private javax.swing.JButton jButton33;
    private javax.swing.JButton jButton34;
    private javax.swing.JButton jButton35;
    private javax.swing.JButton jButton36;
    private javax.swing.JButton jButton37;
    private javax.swing.JButton jButton38;
    private javax.swing.JButton jButton39;
    private javax.swing.JButton jButton40;
    private javax.swing.JButton jButton41;
    private javax.swing.JButton jButton42;
    private javax.swing.JButton jButton43;
    private javax.swing.JButton jButton44;
    private javax.swing.JButton jButton45;
    private javax.swing.JButton jButton46;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JButton jButtonADD;
    private javax.swing.JComboBox<String> jComboBoxDiscountRate;
    private javax.swing.JComboBox<String> jComboBoxDiscountRate1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel37;
    private javax.swing.JLabel jLabel38;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel jLabelsProductPreview;
    private javax.swing.JLabel jLabelsProductPreview1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanelMainSI1;
    private javax.swing.JPanel jPanelSalesInquirySearch;
    private javax.swing.JPanel jPanelSalesInvoiceSearch;
    private javax.swing.JPanel jPanelcustomerSearch1;
    private javax.swing.JPanel jPanelproductSearch;
    private javax.swing.JPanel jPanelproductSearch1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JScrollPane jScrollPane7;
    private javax.swing.JScrollPane jScrollPane8;
    private javax.swing.JScrollPane jScrollPane9;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTable jTable4;
    private javax.swing.JTable jTable5;
    private javax.swing.JTable jTableSCustomer;
    private javax.swing.JTable jTableSalesInuiry1;
    private javax.swing.JTable jTableSalesInvoice;
    private javax.swing.JTable jTablesProduct;
    private javax.swing.JTable jTablesProduct1;
    private javax.swing.JTable jTablesSalesInquiry;
    private javax.swing.JTextArea jTextAreaNote1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField10;
    private javax.swing.JTextField jTextField11;
    private javax.swing.JTextField jTextField12;
    private javax.swing.JTextField jTextField13;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTextField jTextFieldCustomerID;
    private javax.swing.JTextField jTextFieldCustomerId1;
    private javax.swing.JTextField jTextFieldCustomerName;
    private javax.swing.JTextField jTextFieldCustomerName1;
    private javax.swing.JTextField jTextFieldGrandTotal;
    private javax.swing.JTextField jTextFieldGrandTotal1;
    private javax.swing.JTextField jTextFieldSDICustomerId;
    private javax.swing.JTextField jTextFieldSDIpprId1;
    private javax.swing.JTextField jTextFieldSalesInquiryId;
    private javax.swing.JTextField jTextFieldSalesInquiryId1;
    private javax.swing.JTextField jTextFieldSalesInvoiceId;
    private javax.swing.JTextField jTextFieldSearchCustomerId;
    private javax.swing.JTextField jTextFieldSearchCustomerId1;
    private javax.swing.JTextField jTextFieldSearchCustomerName;
    private javax.swing.JTextField jTextFieldSearchCustomerName1;
    private javax.swing.JTextField jTextFieldSearchCustomerPhone;
    private javax.swing.JTextField jTextFieldSearchCustomerPhone1;
    private javax.swing.JTextField jTextFieldTotal;
    private javax.swing.JTextField jTextFieldTotal1;
    private javax.swing.JTextField jTextFieldsDesignId1;
    private javax.swing.JTextField jTextFieldsProductId1;
    private javax.swing.JTextField jTextFieldsProductType1;
    // End of variables declaration//GEN-END:variables
}
